package work.universitycourse.comp1549.Interfaces.Server;

import java.awt.Color;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import work.universitycourse.comp1549.Modules.InterfaceManager;

/**
 *
 * @author Adnan Turan
 * @author Daniel Browne
 * @author Gabriel Netz
 * @author William Phillips
 * 
 */
public class ServerLogsInactive extends javax.swing.JFrame {

    /**
     * Creates new form communicationLogsInactive
     */
    public ServerLogsInactive() {
        initComponents();
        table();
    }

    private void table() {
        mainTable.getTableHeader().setOpaque(false);
        mainTable.getTableHeader().setBackground(Color.white);
        mainTable.getTableHeader().setForeground(new Color(47, 46, 65));

        mainTable.getTableHeader().setFont(new java.awt.Font("Montserrat Medium", 0, 13));

        DefaultTableCellRenderer stringRenderer = (DefaultTableCellRenderer) mainTable.getDefaultRenderer(String.class);
        stringRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) mainTable.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);

        JTableHeader header = mainTable.getTableHeader();
        header.setBorder(new LineBorder(new Color(229, 229, 229), 1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        communicationLogsLabel1 = new javax.swing.JLabel();
        scrollingPane = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        awaitingCommunicationLabel = new javax.swing.JLabel();
        communicationLogsLabel2 = new javax.swing.JLabel();
        middlePanel = new javax.swing.JPanel();
        serverStatusImageLabel = new javax.swing.JLabel();
        serverStatusLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        ipAddressLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        statusValueLabel = new javax.swing.JLabel();
        ipAddressValueLabel = new javax.swing.JLabel();
        portValueLabel = new javax.swing.JLabel();
        reconfigureServerLabel = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        footerTextLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle
                .getBundle("work/universitycourse/comp1549/Interfaces/Server/Bundle"); // NOI18N
        setTitle(bundle.getString("ServerLogsInactive.title")); // NOI18N
        setIconImage(InterfaceManager.programIcon.getImage());
        setMinimumSize(new java.awt.Dimension(854, 519));
        setName("Form"); // NOI18N
        setResizable(false);

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setMaximumSize(new java.awt.Dimension(854, 278));
        topPanel.setMinimumSize(new java.awt.Dimension(854, 278));
        topPanel.setName("topPanel"); // NOI18N
        topPanel.setPreferredSize(new java.awt.Dimension(854, 278));
        InterfaceManager.detectExitRequest(topPanel);

        communicationLogsLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        communicationLogsLabel1.setText(bundle.getString("ServerLogsInactive.communicationLogsLabel1.text_1")); // NOI18N
        communicationLogsLabel1.setName("communicationLogsLabel1"); // NOI18N

        scrollingPane.setName("scrollingPane"); // NOI18N

        mainTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

        }, new String[] { "Origin IP Address", "Destination IP Address", "Request Type", "Request Value" }));
        mainTable.setEnabled(false);
        mainTable.setName("mainTable"); // NOI18N
        mainTable.setRowHeight(30);
        mainTable.setRowSelectionAllowed(false);
        mainTable.getTableHeader().setReorderingAllowed(false);
        scrollingPane.setViewportView(mainTable);

        awaitingCommunicationLabel.setFont(new java.awt.Font("Montserrat Light", 0, 13)); // NOI18N
        awaitingCommunicationLabel.setForeground(new java.awt.Color(196, 196, 202));
        awaitingCommunicationLabel.setText(bundle.getString("ServerLogsInactive.awaitingCommunicationLabel.text_1")); // NOI18N
        awaitingCommunicationLabel.setName("awaitingCommunicationLabel"); // NOI18N

        communicationLogsLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        communicationLogsLabel2.setForeground(new java.awt.Color(0, 36, 109));
        communicationLogsLabel2.setText(bundle.getString("ServerLogsInactive.communicationLogsLabel2.text_1")); // NOI18N
        communicationLogsLabel2.setName("communicationLogsLabel2"); // NOI18N

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(topPanelLayout.createSequentialGroup()
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(topPanelLayout.createSequentialGroup().addGap(292, 292, 292)
                                        .addComponent(communicationLogsLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(communicationLogsLabel2))
                                .addGroup(topPanelLayout.createSequentialGroup().addGap(88, 88, 88).addComponent(
                                        scrollingPane, javax.swing.GroupLayout.PREFERRED_SIZE, 674,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(topPanelLayout.createSequentialGroup().addGap(325, 325, 325)
                                        .addComponent(awaitingCommunicationLabel)))
                        .addGap(261, 261, 261)));
        topPanelLayout.setVerticalGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(topPanelLayout.createSequentialGroup().addGap(47, 47, 47)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(communicationLogsLabel1).addComponent(communicationLogsLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(scrollingPane, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52).addComponent(awaitingCommunicationLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        middlePanel.setBackground(new java.awt.Color(255, 255, 255));
        middlePanel.setName("middlePanel"); // NOI18N

        serverStatusImageLabel
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/broadcast_inactive.png"))); // NOI18N
        serverStatusImageLabel.setName("serverStatusImageLabel"); // NOI18N

        serverStatusLabel.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        serverStatusLabel.setText(bundle.getString("ServerLogsInactive.serverStatusLabel.text_1")); // NOI18N
        serverStatusLabel.setName("serverStatusLabel"); // NOI18N

        statusLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        statusLabel.setText(bundle.getString("ServerLogsInactive.statusLabel.text_1")); // NOI18N
        statusLabel.setName("statusLabel"); // NOI18N

        ipAddressLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        ipAddressLabel.setText(bundle.getString("ServerLogsInactive.ipAddressLabel.text_1")); // NOI18N
        ipAddressLabel.setName("ipAddressLabel"); // NOI18N

        portLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 13)); // NOI18N
        portLabel.setText(bundle.getString("ServerLogsInactive.portLabel.text_1")); // NOI18N
        portLabel.setName("portLabel"); // NOI18N

        statusValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 13)); // NOI18N
        statusValueLabel.setForeground(new java.awt.Color(255, 71, 87));
        statusValueLabel.setText(bundle.getString("ServerLogsInactive.statusValueLabel.text_1")); // NOI18N
        statusValueLabel.setName("statusValueLabel"); // NOI18N

        ipAddressValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 13)); // NOI18N
        ipAddressValueLabel.setText(bundle.getString("ServerLogsInactive.ipAddressValueLabel.text_1")); // NOI18N
        ipAddressValueLabel.setName("ipAddressValueLabel"); // NOI18N

        portValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 13)); // NOI18N
        portValueLabel.setText(bundle.getString("ServerLogsInactive.portValueLabel.text_1")); // NOI18N
        portValueLabel.setName("portValueLabel"); // NOI18N

        reconfigureServerLabel.setFont(new java.awt.Font("Montserrat Light", 0, 9)); // NOI18N
        reconfigureServerLabel.setForeground(new java.awt.Color(112, 161, 255));
        reconfigureServerLabel
                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reconfigure_server.png"))); // NOI18N
        reconfigureServerLabel.setText(bundle.getString("ServerLogsInactive.reconfigureServerLabel.text_1")); // NOI18N
        reconfigureServerLabel.setName("reconfigureServerLabel"); // NOI18N

        javax.swing.GroupLayout middlePanelLayout = new javax.swing.GroupLayout(middlePanel);
        middlePanel.setLayout(middlePanelLayout);
        middlePanelLayout.setHorizontalGroup(middlePanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(middlePanelLayout.createSequentialGroup().addGap(128, 128, 128)
                        .addComponent(serverStatusImageLabel).addGap(114, 114, 114)
                        .addGroup(middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(middlePanelLayout.createSequentialGroup().addComponent(serverStatusLabel)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(middlePanelLayout.createSequentialGroup().addGroup(middlePanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(middlePanelLayout.createSequentialGroup().addGroup(middlePanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(statusLabel).addComponent(statusValueLabel))
                                                .addGap(109, 109, 109)
                                                .addGroup(middlePanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ipAddressLabel)
                                                        .addGroup(middlePanelLayout.createSequentialGroup()
                                                                .addGap(28, 28, 28).addComponent(ipAddressValueLabel,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 17,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(reconfigureServerLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(middlePanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(portLabel).addComponent(portValueLabel,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 17,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(126, 126, 126)))));
        middlePanelLayout.setVerticalGroup(middlePanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(middlePanelLayout.createSequentialGroup().addGap(63, 63, 63).addComponent(serverStatusLabel)
                        .addGap(18, 18, 18)
                        .addGroup(middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(statusLabel).addComponent(ipAddressLabel).addComponent(portLabel))
                        .addGap(18, 18, 18)
                        .addGroup(middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(statusValueLabel).addComponent(ipAddressValueLabel)
                                .addComponent(portValueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reconfigureServerLabel).addContainerGap(63, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        middlePanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(serverStatusImageLabel).addContainerGap()));

        footerPanel.setBackground(new java.awt.Color(255, 255, 255));
        footerPanel.setName("footerPanel"); // NOI18N

        footerTextLabel.setFont(new java.awt.Font("Montserrat", 0, 9)); // NOI18N
        footerTextLabel.setText(bundle.getString("ServerLogsInactive.footerTextLabel.text_1")); // NOI18N
        footerTextLabel.setName("footerTextLabel"); // NOI18N

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout
                .setHorizontalGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(footerPanelLayout.createSequentialGroup().addGap(298, 298, 298)
                                .addComponent(footerTextLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        footerPanelLayout.setVerticalGroup(footerPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(footerPanelLayout
                        .createSequentialGroup().addComponent(footerTextLabel).addGap(0, 11, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                .addComponent(middlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                .addComponent(footerPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 248,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(middlePanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2).addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        getAccessibleContext()
                .setAccessibleName(bundle.getString("ServerLogsInactive.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerLogsInactive.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerLogsInactive.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerLogsInactive.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerLogsInactive.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerLogsInactive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel awaitingCommunicationLabel;
    private javax.swing.JLabel communicationLogsLabel1;
    private javax.swing.JLabel communicationLogsLabel2;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel footerTextLabel;
    private javax.swing.JLabel ipAddressLabel;
    private javax.swing.JLabel ipAddressValueLabel;
    private javax.swing.JTable mainTable;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JLabel portLabel;
    private javax.swing.JLabel portValueLabel;
    private javax.swing.JLabel reconfigureServerLabel;
    private javax.swing.JScrollPane scrollingPane;
    private javax.swing.JLabel serverStatusImageLabel;
    private javax.swing.JLabel serverStatusLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusValueLabel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
