/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package work.universitycourse.comp1549;

import java.awt.Color;

/**
 *
 * @author Daniel Browne
 */
public class ClientUserMessaging extends javax.swing.JFrame {

    /**
     * Creates new form clientUserMessaging
     */
    public ClientUserMessaging() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        headerPanel1 = new javax.swing.JPanel();
        discussionNetLabel = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        clientFeaturesLabel = new javax.swing.JLabel();
        userMessagingLabel = new javax.swing.JLabel();
        updateLogsLabel = new javax.swing.JLabel();
        exitApplicationLabel = new javax.swing.JLabel();
        clientDetailsPanel1 = new javax.swing.JPanel();
        clientDetailsIcon = new javax.swing.JLabel();
        clientDetailsLabel1 = new javax.swing.JLabel();
        clientDetailsLabel2 = new javax.swing.JLabel();
        serverDetailsPanel1 = new javax.swing.JPanel();
        server_details_icon = new javax.swing.JLabel();
        serverDetailsLabel1 = new javax.swing.JLabel();
        serverDetailsLabel2 = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        footerTextLabel = new javax.swing.JLabel();
        userMessagingTopPanel = new javax.swing.JPanel();
        userMessagingIconLabel = new javax.swing.JLabel();
        userMessagingLabel1 = new javax.swing.JLabel();
        userMessagingLabel2 = new javax.swing.JLabel();
        userMessagingSidePanel = new javax.swing.JPanel();
        usersLabel = new javax.swing.JLabel();
        userLabel1 = new javax.swing.JLabel();
        rightArrowIcon1 = new javax.swing.JLabel();
        userLabel2 = new javax.swing.JLabel();
        userLabel3 = new javax.swing.JLabel();
        userLabel4 = new javax.swing.JLabel();
        userLabel5 = new javax.swing.JLabel();
        rightArrowIcon2 = new javax.swing.JLabel();
        rightArrowIcon3 = new javax.swing.JLabel();
        rightArrowIcon4 = new javax.swing.JLabel();
        rightArrowIcon5 = new javax.swing.JLabel();
        userMessagingMainPanel = new javax.swing.JPanel();
        userMessagesTextfield = new RoundJTextField();
        userMessagesButton = new javax.swing.JButton();
        messagesLabel = new javax.swing.JLabel();
        clientDetailsPanel2 = new javax.swing.JPanel();
        clientDetailsIPAddressLabel = new javax.swing.JLabel();
        clientDetailsIPAddressValueLabel = new javax.swing.JLabel();
        clientDetailsConnectionPortLabel = new javax.swing.JLabel();
        clientDetailsConnectionPortValueLabel = new javax.swing.JLabel();
        clientDetailsAssignedIDNumberLabel = new javax.swing.JLabel();
        clientDetailsAssignedIDNumberValueLabel = new javax.swing.JLabel();
        serverDetailsPanel2 = new javax.swing.JPanel();
        serverDetailsIPAddressLabel = new javax.swing.JLabel();
        serverDetailsIPAddressValueLabel = new javax.swing.JLabel();
        serverDetailsConnectionPortLabel = new javax.swing.JLabel();
        serverDetailsConnectionPortValueLabel = new javax.swing.JLabel();
        serverDetailsConnectionStatusLabel = new javax.swing.JLabel();
        serverDetailsConnectionStatusValueLabel = new javax.swing.JLabel();
        headerPanel2 = new javax.swing.JPanel();
        navIconLabel = new javax.swing.JLabel();
        clientControlPanelLabel1 = new javax.swing.JLabel();
        clientControlPanelLabel2 = new javax.swing.JLabel();

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black_arrow.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 244, 250));
        setMinimumSize(new java.awt.Dimension(1090, 708));
        setResizable(false);

        headerPanel1.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel1.setPreferredSize(new java.awt.Dimension(153, 43));

        discussionNetLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        discussionNetLabel.setForeground(new java.awt.Color(0, 36, 109));
        discussionNetLabel.setText("DiscussionNet");

        javax.swing.GroupLayout headerPanel1Layout = new javax.swing.GroupLayout(headerPanel1);
        headerPanel1.setLayout(headerPanel1Layout);
        headerPanel1Layout.setHorizontalGroup(
            headerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(discussionNetLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanel1Layout.setVerticalGroup(
            headerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(discussionNetLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidePanel.setBackground(new java.awt.Color(0, 36, 109));
        sidePanel.setForeground(new java.awt.Color(0, 36, 109));
        sidePanel.setToolTipText("");
        sidePanel.setPreferredSize(new java.awt.Dimension(154, 60));

        clientFeaturesLabel.setBackground(new java.awt.Color(255, 255, 255));
        clientFeaturesLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientFeaturesLabel.setForeground(new java.awt.Color(255, 255, 255));
        clientFeaturesLabel.setText("CLIENT FEATURES");

        userMessagingLabel.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        userMessagingLabel.setForeground(new java.awt.Color(255, 255, 255));
        userMessagingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mail_icon.png"))); // NOI18N
        userMessagingLabel.setText("User Messaging");

        updateLogsLabel.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        updateLogsLabel.setForeground(new java.awt.Color(255, 255, 255));
        updateLogsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file_icon.png"))); // NOI18N
        updateLogsLabel.setText("Update Logs");

        exitApplicationLabel.setBackground(new java.awt.Color(255, 255, 255));
        exitApplicationLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        exitApplicationLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitApplicationLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit_button.png"))); // NOI18N
        exitApplicationLabel.setText("Exit Application");
        exitApplicationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitApplicationLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitApplicationLabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitApplicationLabel)
                    .addComponent(clientFeaturesLabel)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateLogsLabel)
                            .addComponent(userMessagingLabel))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(clientFeaturesLabel)
                .addGap(18, 18, 18)
                .addComponent(userMessagingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateLogsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitApplicationLabel)
                .addGap(25, 25, 25))
        );

        clientDetailsPanel1.setBackground(new java.awt.Color(255, 255, 255));
        clientDetailsPanel1.setPreferredSize(new java.awt.Dimension(322, 100));

        clientDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client_details.png"))); // NOI18N

        clientDetailsLabel1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        clientDetailsLabel1.setText("Client");

        clientDetailsLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        clientDetailsLabel2.setForeground(new java.awt.Color(0, 36, 109));
        clientDetailsLabel2.setText("Details");

        javax.swing.GroupLayout clientDetailsPanel1Layout = new javax.swing.GroupLayout(clientDetailsPanel1);
        clientDetailsPanel1.setLayout(clientDetailsPanel1Layout);
        clientDetailsPanel1Layout.setHorizontalGroup(
            clientDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(clientDetailsIcon)
                .addGap(37, 37, 37)
                .addComponent(clientDetailsLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientDetailsLabel2)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        clientDetailsPanel1Layout.setVerticalGroup(
            clientDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(clientDetailsIcon)
                .addGap(22, 22, 22))
            .addGroup(clientDetailsPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(clientDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientDetailsLabel1)
                    .addComponent(clientDetailsLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        serverDetailsPanel1.setBackground(new java.awt.Color(255, 255, 255));
        serverDetailsPanel1.setPreferredSize(new java.awt.Dimension(322, 100));

        server_details_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server_details.png"))); // NOI18N

        serverDetailsLabel1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        serverDetailsLabel1.setText("Server");

        serverDetailsLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        serverDetailsLabel2.setForeground(new java.awt.Color(0, 36, 109));
        serverDetailsLabel2.setText("Details");

        javax.swing.GroupLayout serverDetailsPanel1Layout = new javax.swing.GroupLayout(serverDetailsPanel1);
        serverDetailsPanel1.setLayout(serverDetailsPanel1Layout);
        serverDetailsPanel1Layout.setHorizontalGroup(
            serverDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serverDetailsPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(server_details_icon)
                .addGap(38, 38, 38)
                .addComponent(serverDetailsLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serverDetailsLabel2)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        serverDetailsPanel1Layout.setVerticalGroup(
            serverDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serverDetailsPanel1Layout.createSequentialGroup()
                .addGroup(serverDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(serverDetailsPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(server_details_icon))
                    .addGroup(serverDetailsPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(serverDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serverDetailsLabel1)
                            .addComponent(serverDetailsLabel2))))
                .addContainerGap())
        );

        footerPanel.setBackground(new java.awt.Color(255, 255, 255));
        footerPanel.setPreferredSize(new java.awt.Dimension(936, 20));

        footerTextLabel.setText("DiscussionNet V1.0 - © Code Squad 2021 - Software Licenses");

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(footerTextLabel)
                .addGap(308, 308, 308))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(footerTextLabel))
        );

        userMessagingTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        userMessagingTopPanel.setMinimumSize(new java.awt.Dimension(93, 100));
        userMessagingTopPanel.setPreferredSize(new java.awt.Dimension(894, 93));

        userMessagingIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_messaging.png"))); // NOI18N

        userMessagingLabel1.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        userMessagingLabel1.setText("User");

        userMessagingLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 28)); // NOI18N
        userMessagingLabel2.setForeground(new java.awt.Color(0, 36, 109));
        userMessagingLabel2.setText("Messaging");

        javax.swing.GroupLayout userMessagingTopPanelLayout = new javax.swing.GroupLayout(userMessagingTopPanel);
        userMessagingTopPanel.setLayout(userMessagingTopPanelLayout);
        userMessagingTopPanelLayout.setHorizontalGroup(
            userMessagingTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMessagingTopPanelLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(userMessagingIconLabel)
                .addGap(18, 18, 18)
                .addComponent(userMessagingLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userMessagingLabel2)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        userMessagingTopPanelLayout.setVerticalGroup(
            userMessagingTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMessagingTopPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(userMessagingTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userMessagingIconLabel)
                    .addGroup(userMessagingTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userMessagingLabel2)
                        .addComponent(userMessagingLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userMessagingSidePanel.setBackground(new java.awt.Color(255, 255, 255));
        userMessagingSidePanel.setPreferredSize(new java.awt.Dimension(156, 298));

        usersLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        usersLabel.setText("Users");

        userLabel1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        userLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel1.setText("User 100");
        userLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rightArrowIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black_arrow.png"))); // NOI18N

        userLabel2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        userLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel2.setText("User 101");
        userLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        userLabel3.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        userLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel3.setText("User 102");
        userLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        userLabel4.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        userLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel4.setText("User 103");
        userLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        userLabel5.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        userLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel5.setText("User 104");
        userLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rightArrowIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black_arrow.png"))); // NOI18N

        rightArrowIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black_arrow.png"))); // NOI18N

        rightArrowIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black_arrow.png"))); // NOI18N

        rightArrowIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black_arrow.png"))); // NOI18N

        javax.swing.GroupLayout userMessagingSidePanelLayout = new javax.swing.GroupLayout(userMessagingSidePanel);
        userMessagingSidePanel.setLayout(userMessagingSidePanelLayout);
        userMessagingSidePanelLayout.setHorizontalGroup(
            userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                        .addComponent(usersLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                        .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                                .addComponent(userLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rightArrowIcon1))
                            .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                                .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userLabel5)
                                    .addComponent(userLabel4)
                                    .addComponent(userLabel3)
                                    .addComponent(userLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rightArrowIcon2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rightArrowIcon3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rightArrowIcon4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rightArrowIcon5, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(27, 27, 27))))
        );
        userMessagingSidePanelLayout.setVerticalGroup(
            userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                        .addComponent(usersLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userLabel1))
                    .addComponent(rightArrowIcon1))
                .addGap(18, 18, 18)
                .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                        .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userLabel2)
                            .addComponent(rightArrowIcon2))
                        .addGap(18, 18, 18)
                        .addComponent(userLabel3))
                    .addComponent(rightArrowIcon3))
                .addGap(18, 18, 18)
                .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rightArrowIcon4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userLabel5)
                    .addComponent(rightArrowIcon5))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        userMessagingMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        userMessagingMainPanel.setPreferredSize(new java.awt.Dimension(737, 298));

        userMessagesTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMessagesTextfieldActionPerformed(evt);
            }
        });

        userMessagesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/super_small_button_background.png"))); // NOI18N
        userMessagesButton.setBorder(null);
        userMessagesButton.setContentAreaFilled(false);
        userMessagesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        messagesLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        messagesLabel.setText("Messages");

        javax.swing.GroupLayout userMessagingMainPanelLayout = new javax.swing.GroupLayout(userMessagingMainPanel);
        userMessagingMainPanel.setLayout(userMessagingMainPanelLayout);
        userMessagingMainPanelLayout.setHorizontalGroup(
            userMessagingMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMessagingMainPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(userMessagingMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messagesLabel)
                    .addGroup(userMessagingMainPanelLayout.createSequentialGroup()
                        .addComponent(userMessagesTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userMessagesButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userMessagingMainPanelLayout.setVerticalGroup(
            userMessagingMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMessagingMainPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(messagesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userMessagingMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMessagingMainPanelLayout.createSequentialGroup()
                        .addComponent(userMessagesButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMessagingMainPanelLayout.createSequentialGroup()
                        .addComponent(userMessagesTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        clientDetailsPanel2.setBackground(new java.awt.Color(255, 255, 255));
        clientDetailsPanel2.setMinimumSize(new java.awt.Dimension(322, 92));

        clientDetailsIPAddressLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        clientDetailsIPAddressLabel.setText("IP Address");

        clientDetailsIPAddressValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        clientDetailsIPAddressValueLabel.setText("0.0.0.0");

        clientDetailsConnectionPortLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        clientDetailsConnectionPortLabel.setText("Connection Port");

        clientDetailsConnectionPortValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        clientDetailsConnectionPortValueLabel.setText("69420");

        clientDetailsAssignedIDNumberLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        clientDetailsAssignedIDNumberLabel.setText("Assigned ID Number");

        clientDetailsAssignedIDNumberValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        clientDetailsAssignedIDNumberValueLabel.setForeground(new java.awt.Color(112, 161, 255));
        clientDetailsAssignedIDNumberValueLabel.setText("105");

        javax.swing.GroupLayout clientDetailsPanel2Layout = new javax.swing.GroupLayout(clientDetailsPanel2);
        clientDetailsPanel2.setLayout(clientDetailsPanel2Layout);
        clientDetailsPanel2Layout.setHorizontalGroup(
            clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientDetailsIPAddressLabel)
                    .addComponent(clientDetailsIPAddressValueLabel))
                .addGap(52, 52, 52)
                .addGroup(clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientDetailsConnectionPortLabel)
                    .addComponent(clientDetailsConnectionPortValueLabel))
                .addGap(45, 45, 45)
                .addGroup(clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientDetailsAssignedIDNumberValueLabel)
                    .addComponent(clientDetailsAssignedIDNumberLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clientDetailsPanel2Layout.setVerticalGroup(
            clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientDetailsIPAddressLabel)
                    .addComponent(clientDetailsConnectionPortLabel)
                    .addComponent(clientDetailsAssignedIDNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientDetailsIPAddressValueLabel)
                    .addComponent(clientDetailsConnectionPortValueLabel)
                    .addComponent(clientDetailsAssignedIDNumberValueLabel))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        serverDetailsPanel2.setBackground(new java.awt.Color(255, 255, 255));
        serverDetailsPanel2.setPreferredSize(new java.awt.Dimension(322, 92));

        serverDetailsIPAddressLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        serverDetailsIPAddressLabel.setText("IP Address");

        serverDetailsIPAddressValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        serverDetailsIPAddressValueLabel.setText("0.0.0.0");

        serverDetailsConnectionPortLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        serverDetailsConnectionPortLabel.setText("Connection Port");

        serverDetailsConnectionPortValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        serverDetailsConnectionPortValueLabel.setText("69420");

        serverDetailsConnectionStatusLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        serverDetailsConnectionStatusLabel.setText("Connection Status");

        serverDetailsConnectionStatusValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        serverDetailsConnectionStatusValueLabel.setForeground(new java.awt.Color(46, 213, 116));
        serverDetailsConnectionStatusValueLabel.setText("Connected");

        javax.swing.GroupLayout serverDetailsPanel2Layout = new javax.swing.GroupLayout(serverDetailsPanel2);
        serverDetailsPanel2.setLayout(serverDetailsPanel2Layout);
        serverDetailsPanel2Layout.setHorizontalGroup(
            serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serverDetailsPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverDetailsIPAddressLabel)
                    .addComponent(serverDetailsIPAddressValueLabel))
                .addGap(50, 50, 50)
                .addGroup(serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverDetailsConnectionPortLabel)
                    .addComponent(serverDetailsConnectionPortValueLabel))
                .addGap(48, 48, 48)
                .addGroup(serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverDetailsConnectionStatusValueLabel)
                    .addComponent(serverDetailsConnectionStatusLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        serverDetailsPanel2Layout.setVerticalGroup(
            serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serverDetailsPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverDetailsIPAddressLabel)
                    .addComponent(serverDetailsConnectionPortLabel)
                    .addComponent(serverDetailsConnectionStatusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverDetailsIPAddressValueLabel)
                    .addComponent(serverDetailsConnectionPortValueLabel)
                    .addComponent(serverDetailsConnectionStatusValueLabel))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        headerPanel2.setBackground(new java.awt.Color(255, 255, 255));

        navIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nav_icon.png"))); // NOI18N

        clientControlPanelLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        clientControlPanelLabel1.setForeground(new java.awt.Color(0, 36, 109));
        clientControlPanelLabel1.setText("Client");

        clientControlPanelLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        clientControlPanelLabel2.setForeground(new java.awt.Color(0, 36, 109));
        clientControlPanelLabel2.setText("Control Panel");

        javax.swing.GroupLayout headerPanel2Layout = new javax.swing.GroupLayout(headerPanel2);
        headerPanel2.setLayout(headerPanel2Layout);
        headerPanel2Layout.setHorizontalGroup(
            headerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navIconLabel)
                .addGap(142, 142, 142)
                .addComponent(clientControlPanelLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientControlPanelLabel2)
                .addContainerGap(627, Short.MAX_VALUE))
        );
        headerPanel2Layout.setVerticalGroup(
            headerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(headerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navIconLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(headerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clientControlPanelLabel2)
                        .addComponent(clientControlPanelLabel1)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(headerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(serverDetailsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(serverDetailsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clientDetailsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(clientDetailsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userMessagingSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addGap(2, 2, 2)
                                .addComponent(userMessagingMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(userMessagingTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(headerPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(headerPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientDetailsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientDetailsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serverDetailsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serverDetailsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(userMessagingTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userMessagingSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(userMessagingMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userMessagesTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMessagesTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userMessagesTextfieldActionPerformed

    private void exitApplicationLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitApplicationLabelMouseClicked

    }//GEN-LAST:event_exitApplicationLabelMouseClicked

    private void exitApplicationLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitApplicationLabelMouseEntered

    }//GEN-LAST:event_exitApplicationLabelMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUserMessaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUserMessaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUserMessaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUserMessaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientUserMessaging().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clientControlPanelLabel1;
    private javax.swing.JLabel clientControlPanelLabel2;
    private javax.swing.JLabel clientDetailsAssignedIDNumberLabel;
    private javax.swing.JLabel clientDetailsAssignedIDNumberValueLabel;
    private javax.swing.JLabel clientDetailsConnectionPortLabel;
    private javax.swing.JLabel clientDetailsConnectionPortValueLabel;
    private javax.swing.JLabel clientDetailsIPAddressLabel;
    private javax.swing.JLabel clientDetailsIPAddressValueLabel;
    private javax.swing.JLabel clientDetailsIcon;
    private javax.swing.JLabel clientDetailsLabel1;
    private javax.swing.JLabel clientDetailsLabel2;
    private javax.swing.JPanel clientDetailsPanel1;
    private javax.swing.JPanel clientDetailsPanel2;
    private javax.swing.JLabel clientFeaturesLabel;
    private javax.swing.JLabel discussionNetLabel;
    private javax.swing.JLabel exitApplicationLabel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel footerTextLabel;
    private javax.swing.JPanel headerPanel1;
    private javax.swing.JPanel headerPanel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel messagesLabel;
    private javax.swing.JLabel navIconLabel;
    private javax.swing.JLabel rightArrowIcon1;
    private javax.swing.JLabel rightArrowIcon2;
    private javax.swing.JLabel rightArrowIcon3;
    private javax.swing.JLabel rightArrowIcon4;
    private javax.swing.JLabel rightArrowIcon5;
    private javax.swing.JLabel serverDetailsConnectionPortLabel;
    private javax.swing.JLabel serverDetailsConnectionPortValueLabel;
    private javax.swing.JLabel serverDetailsConnectionStatusLabel;
    private javax.swing.JLabel serverDetailsConnectionStatusValueLabel;
    private javax.swing.JLabel serverDetailsIPAddressLabel;
    private javax.swing.JLabel serverDetailsIPAddressValueLabel;
    private javax.swing.JLabel serverDetailsLabel1;
    private javax.swing.JLabel serverDetailsLabel2;
    private javax.swing.JPanel serverDetailsPanel1;
    private javax.swing.JPanel serverDetailsPanel2;
    private javax.swing.JLabel server_details_icon;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel updateLogsLabel;
    private javax.swing.JLabel userLabel1;
    private javax.swing.JLabel userLabel2;
    private javax.swing.JLabel userLabel3;
    private javax.swing.JLabel userLabel4;
    private javax.swing.JLabel userLabel5;
    private javax.swing.JButton userMessagesButton;
    private javax.swing.JTextField userMessagesTextfield;
    private javax.swing.JLabel userMessagingIconLabel;
    private javax.swing.JLabel userMessagingLabel;
    private javax.swing.JLabel userMessagingLabel1;
    private javax.swing.JLabel userMessagingLabel2;
    private javax.swing.JPanel userMessagingMainPanel;
    private javax.swing.JPanel userMessagingSidePanel;
    private javax.swing.JPanel userMessagingTopPanel;
    private javax.swing.JLabel usersLabel;
    // End of variables declaration//GEN-END:variables
}
