/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package work.universitycourse.comp1549;

import java.awt.Color;

/**
 *
 * @author Daniel Browne
 */
public class clientUserMessaging extends javax.swing.JFrame {

    /**
     * Creates new form clientUserMessaging
     */
    public clientUserMessaging() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        header_panel_1 = new javax.swing.JPanel();
        discussionNet_title = new javax.swing.JLabel();
        side_panel = new javax.swing.JPanel();
        client_features_label = new javax.swing.JLabel();
        user_messaging_label = new javax.swing.JLabel();
        update_logs_label = new javax.swing.JLabel();
        exit_app_label = new javax.swing.JLabel();
        client_details_panel_1 = new javax.swing.JPanel();
        client_details_icon = new javax.swing.JLabel();
        client_details_label_1 = new javax.swing.JLabel();
        client_details_label_2 = new javax.swing.JLabel();
        server_details_panel_1 = new javax.swing.JPanel();
        server_details_icon = new javax.swing.JLabel();
        server_details_label_1 = new javax.swing.JLabel();
        server_details_label_2 = new javax.swing.JLabel();
        footer_panel = new javax.swing.JPanel();
        footer_text = new javax.swing.JLabel();
        user_messaging_top_panel = new javax.swing.JPanel();
        user_messaging_icon = new javax.swing.JLabel();
        user_messaging_label_1 = new javax.swing.JLabel();
        user_messaging_label_2 = new javax.swing.JLabel();
        user_messaging_side_panel = new javax.swing.JPanel();
        users_label = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        right_arrow_icon_1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        right_arrow_icon_2 = new javax.swing.JLabel();
        right_arrow_icon_3 = new javax.swing.JLabel();
        right_arrow_icon_4 = new javax.swing.JLabel();
        right_arrow_icon_5 = new javax.swing.JLabel();
        user_messaging_main_panel = new javax.swing.JPanel();
        user_messages_textfield = new javax.swing.JTextField();
        user_messages_send_button = new javax.swing.JButton();
        messages_label = new javax.swing.JLabel();
        client_details_panel_2 = new javax.swing.JPanel();
        client_details_IP_label = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        client_details_port_label = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        client_details_ID_number_label = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        server_details_panel_2 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        header_panel_2 = new javax.swing.JPanel();
        nav_icon = new javax.swing.JLabel();
        client_control_panel_label_1 = new javax.swing.JLabel();
        client_control_panel_label_2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black_arrow.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 244, 250));
        setMaximumSize(new java.awt.Dimension(1090, 708));
        setMinimumSize(new java.awt.Dimension(1090, 708));
        setPreferredSize(new java.awt.Dimension(1090, 708));
        setResizable(false);

        header_panel_1.setBackground(new java.awt.Color(255, 255, 255));
        header_panel_1.setPreferredSize(new java.awt.Dimension(153, 43));

        discussionNet_title.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        discussionNet_title.setForeground(new java.awt.Color(0, 36, 109));
        discussionNet_title.setText("DiscussionNet");

        javax.swing.GroupLayout header_panel_1Layout = new javax.swing.GroupLayout(header_panel_1);
        header_panel_1.setLayout(header_panel_1Layout);
        header_panel_1Layout.setHorizontalGroup(
            header_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panel_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(discussionNet_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header_panel_1Layout.setVerticalGroup(
            header_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panel_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(discussionNet_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_panel.setBackground(new java.awt.Color(0, 36, 109));
        side_panel.setForeground(new java.awt.Color(0, 36, 109));
        side_panel.setToolTipText("");
        side_panel.setPreferredSize(new java.awt.Dimension(154, 60));

        client_features_label.setBackground(new java.awt.Color(255, 255, 255));
        client_features_label.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        client_features_label.setForeground(new java.awt.Color(255, 255, 255));
        client_features_label.setText("CLIENT FEATURES");

        user_messaging_label.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        user_messaging_label.setForeground(new java.awt.Color(255, 255, 255));
        user_messaging_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mail_icon.png"))); // NOI18N
        user_messaging_label.setText("User Messaging");

        update_logs_label.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        update_logs_label.setForeground(new java.awt.Color(255, 255, 255));
        update_logs_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file_icon.png"))); // NOI18N
        update_logs_label.setText("Update Logs");

        exit_app_label.setBackground(new java.awt.Color(255, 255, 255));
        exit_app_label.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        exit_app_label.setForeground(new java.awt.Color(255, 255, 255));
        exit_app_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit_button.png"))); // NOI18N
        exit_app_label.setText("Exit Application");
        exit_app_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_app_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_app_labelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout side_panelLayout = new javax.swing.GroupLayout(side_panel);
        side_panel.setLayout(side_panelLayout);
        side_panelLayout.setHorizontalGroup(
            side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit_app_label)
                    .addComponent(client_features_label)
                    .addGroup(side_panelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_logs_label)
                            .addComponent(user_messaging_label))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        side_panelLayout.setVerticalGroup(
            side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(client_features_label)
                .addGap(18, 18, 18)
                .addComponent(user_messaging_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update_logs_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit_app_label)
                .addGap(25, 25, 25))
        );

        client_details_panel_1.setBackground(new java.awt.Color(255, 255, 255));
        client_details_panel_1.setPreferredSize(new java.awt.Dimension(322, 100));

        client_details_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client_details.png"))); // NOI18N

        client_details_label_1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        client_details_label_1.setText("Client");

        client_details_label_2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        client_details_label_2.setForeground(new java.awt.Color(0, 36, 109));
        client_details_label_2.setText("Details");

        javax.swing.GroupLayout client_details_panel_1Layout = new javax.swing.GroupLayout(client_details_panel_1);
        client_details_panel_1.setLayout(client_details_panel_1Layout);
        client_details_panel_1Layout.setHorizontalGroup(
            client_details_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(client_details_panel_1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(client_details_icon)
                .addGap(37, 37, 37)
                .addComponent(client_details_label_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(client_details_label_2)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        client_details_panel_1Layout.setVerticalGroup(
            client_details_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(client_details_panel_1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(client_details_icon)
                .addGap(22, 22, 22))
            .addGroup(client_details_panel_1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(client_details_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(client_details_label_1)
                    .addComponent(client_details_label_2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        server_details_panel_1.setBackground(new java.awt.Color(255, 255, 255));
        server_details_panel_1.setPreferredSize(new java.awt.Dimension(322, 100));

        server_details_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/server_details.png"))); // NOI18N

        server_details_label_1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        server_details_label_1.setText("Server");

        server_details_label_2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        server_details_label_2.setForeground(new java.awt.Color(0, 36, 109));
        server_details_label_2.setText("Details");

        javax.swing.GroupLayout server_details_panel_1Layout = new javax.swing.GroupLayout(server_details_panel_1);
        server_details_panel_1.setLayout(server_details_panel_1Layout);
        server_details_panel_1Layout.setHorizontalGroup(
            server_details_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(server_details_panel_1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(server_details_icon)
                .addGap(38, 38, 38)
                .addComponent(server_details_label_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(server_details_label_2)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        server_details_panel_1Layout.setVerticalGroup(
            server_details_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(server_details_panel_1Layout.createSequentialGroup()
                .addGroup(server_details_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(server_details_panel_1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(server_details_icon))
                    .addGroup(server_details_panel_1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(server_details_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(server_details_label_1)
                            .addComponent(server_details_label_2))))
                .addContainerGap())
        );

        footer_panel.setBackground(new java.awt.Color(255, 255, 255));
        footer_panel.setPreferredSize(new java.awt.Dimension(936, 20));

        footer_text.setText("DiscussionNet V1.0 - © Code Squad 2021 - Software Licenses");

        javax.swing.GroupLayout footer_panelLayout = new javax.swing.GroupLayout(footer_panel);
        footer_panel.setLayout(footer_panelLayout);
        footer_panelLayout.setHorizontalGroup(
            footer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footer_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(footer_text)
                .addGap(308, 308, 308))
        );
        footer_panelLayout.setVerticalGroup(
            footer_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footer_panelLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(footer_text))
        );

        user_messaging_top_panel.setBackground(new java.awt.Color(255, 255, 255));
        user_messaging_top_panel.setMinimumSize(new java.awt.Dimension(93, 100));
        user_messaging_top_panel.setPreferredSize(new java.awt.Dimension(894, 93));

        user_messaging_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_messaging.png"))); // NOI18N

        user_messaging_label_1.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        user_messaging_label_1.setText("User");

        user_messaging_label_2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 28)); // NOI18N
        user_messaging_label_2.setForeground(new java.awt.Color(0, 36, 109));
        user_messaging_label_2.setText("Messaging");

        javax.swing.GroupLayout user_messaging_top_panelLayout = new javax.swing.GroupLayout(user_messaging_top_panel);
        user_messaging_top_panel.setLayout(user_messaging_top_panelLayout);
        user_messaging_top_panelLayout.setHorizontalGroup(
            user_messaging_top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_messaging_top_panelLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(user_messaging_icon)
                .addGap(18, 18, 18)
                .addComponent(user_messaging_label_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_messaging_label_2)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        user_messaging_top_panelLayout.setVerticalGroup(
            user_messaging_top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_messaging_top_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(user_messaging_top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user_messaging_icon)
                    .addGroup(user_messaging_top_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(user_messaging_label_2)
                        .addComponent(user_messaging_label_1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        user_messaging_side_panel.setBackground(new java.awt.Color(255, 255, 255));
        user_messaging_side_panel.setPreferredSize(new java.awt.Dimension(156, 298));

        users_label.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        users_label.setText("Users");

        jLabel16.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("User 100");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        right_arrow_icon_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black_arrow.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("User 101");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel19.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("User 102");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel20.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("User 103");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel21.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("User 104");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        right_arrow_icon_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black_arrow.png"))); // NOI18N

        right_arrow_icon_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black_arrow.png"))); // NOI18N

        right_arrow_icon_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black_arrow.png"))); // NOI18N

        right_arrow_icon_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black_arrow.png"))); // NOI18N

        javax.swing.GroupLayout user_messaging_side_panelLayout = new javax.swing.GroupLayout(user_messaging_side_panel);
        user_messaging_side_panel.setLayout(user_messaging_side_panelLayout);
        user_messaging_side_panelLayout.setHorizontalGroup(
            user_messaging_side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_messaging_side_panelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(user_messaging_side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(user_messaging_side_panelLayout.createSequentialGroup()
                        .addComponent(users_label)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(user_messaging_side_panelLayout.createSequentialGroup()
                        .addGroup(user_messaging_side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(user_messaging_side_panelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(right_arrow_icon_1))
                            .addGroup(user_messaging_side_panelLayout.createSequentialGroup()
                                .addGroup(user_messaging_side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(user_messaging_side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(right_arrow_icon_2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(right_arrow_icon_3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(right_arrow_icon_4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(right_arrow_icon_5, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(27, 27, 27))))
        );
        user_messaging_side_panelLayout.setVerticalGroup(
            user_messaging_side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_messaging_side_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(user_messaging_side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(user_messaging_side_panelLayout.createSequentialGroup()
                        .addComponent(users_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addComponent(right_arrow_icon_1))
                .addGap(18, 18, 18)
                .addGroup(user_messaging_side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(user_messaging_side_panelLayout.createSequentialGroup()
                        .addGroup(user_messaging_side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(right_arrow_icon_2))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19))
                    .addComponent(right_arrow_icon_3))
                .addGap(18, 18, 18)
                .addGroup(user_messaging_side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(right_arrow_icon_4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(user_messaging_side_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(right_arrow_icon_5))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        user_messaging_main_panel.setBackground(new java.awt.Color(255, 255, 255));
        user_messaging_main_panel.setPreferredSize(new java.awt.Dimension(737, 298));

        user_messages_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_messages_textfieldActionPerformed(evt);
            }
        });

        user_messages_send_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/super_small_button_background.png"))); // NOI18N
        user_messages_send_button.setBorder(null);
        user_messages_send_button.setContentAreaFilled(false);
        user_messages_send_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        messages_label.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        messages_label.setText("Messages");

        javax.swing.GroupLayout user_messaging_main_panelLayout = new javax.swing.GroupLayout(user_messaging_main_panel);
        user_messaging_main_panel.setLayout(user_messaging_main_panelLayout);
        user_messaging_main_panelLayout.setHorizontalGroup(
            user_messaging_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_messaging_main_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(user_messaging_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messages_label)
                    .addGroup(user_messaging_main_panelLayout.createSequentialGroup()
                        .addComponent(user_messages_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user_messages_send_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        user_messaging_main_panelLayout.setVerticalGroup(
            user_messaging_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_messaging_main_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(messages_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(user_messaging_main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_messaging_main_panelLayout.createSequentialGroup()
                        .addComponent(user_messages_send_button)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_messaging_main_panelLayout.createSequentialGroup()
                        .addComponent(user_messages_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        client_details_panel_2.setBackground(new java.awt.Color(255, 255, 255));
        client_details_panel_2.setMinimumSize(new java.awt.Dimension(322, 92));

        client_details_IP_label.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        client_details_IP_label.setText("IP Address");

        jLabel30.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        jLabel30.setText("0.0.0.0");

        client_details_port_label.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        client_details_port_label.setText("Connection Port");

        jLabel32.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        jLabel32.setText("69420");

        client_details_ID_number_label.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        client_details_ID_number_label.setText("Assigned ID Number");

        jLabel34.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(112, 161, 255));
        jLabel34.setText("105");

        javax.swing.GroupLayout client_details_panel_2Layout = new javax.swing.GroupLayout(client_details_panel_2);
        client_details_panel_2.setLayout(client_details_panel_2Layout);
        client_details_panel_2Layout.setHorizontalGroup(
            client_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(client_details_panel_2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(client_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(client_details_IP_label)
                    .addComponent(jLabel30))
                .addGap(52, 52, 52)
                .addGroup(client_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(client_details_port_label)
                    .addComponent(jLabel32))
                .addGap(45, 45, 45)
                .addGroup(client_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(client_details_ID_number_label))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        client_details_panel_2Layout.setVerticalGroup(
            client_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(client_details_panel_2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(client_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(client_details_IP_label)
                    .addComponent(client_details_port_label)
                    .addComponent(client_details_ID_number_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(client_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel32)
                    .addComponent(jLabel34))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        server_details_panel_2.setBackground(new java.awt.Color(255, 255, 255));
        server_details_panel_2.setPreferredSize(new java.awt.Dimension(322, 92));

        jLabel35.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        jLabel35.setText("IP Address");

        jLabel36.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        jLabel36.setText("0.0.0.0");

        jLabel37.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        jLabel37.setText("Connection Port");

        jLabel38.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        jLabel38.setText("69420");

        jLabel39.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        jLabel39.setText("Connection Status");

        jLabel40.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(46, 213, 116));
        jLabel40.setText("Connected");

        javax.swing.GroupLayout server_details_panel_2Layout = new javax.swing.GroupLayout(server_details_panel_2);
        server_details_panel_2.setLayout(server_details_panel_2Layout);
        server_details_panel_2Layout.setHorizontalGroup(
            server_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(server_details_panel_2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(server_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(50, 50, 50)
                .addGroup(server_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addGap(48, 48, 48)
                .addGroup(server_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel39))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        server_details_panel_2Layout.setVerticalGroup(
            server_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(server_details_panel_2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(server_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel37)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(server_details_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel38)
                    .addComponent(jLabel40))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        header_panel_2.setBackground(new java.awt.Color(255, 255, 255));

        nav_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nav_icon.png"))); // NOI18N

        client_control_panel_label_1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        client_control_panel_label_1.setForeground(new java.awt.Color(0, 36, 109));
        client_control_panel_label_1.setText("Client");

        client_control_panel_label_2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        client_control_panel_label_2.setForeground(new java.awt.Color(0, 36, 109));
        client_control_panel_label_2.setText("Control Panel");

        javax.swing.GroupLayout header_panel_2Layout = new javax.swing.GroupLayout(header_panel_2);
        header_panel_2.setLayout(header_panel_2Layout);
        header_panel_2Layout.setHorizontalGroup(
            header_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panel_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(header_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(header_panel_2Layout.createSequentialGroup()
                        .addComponent(nav_icon)
                        .addGap(47, 47, 47)
                        .addComponent(client_control_panel_label_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(client_control_panel_label_2))
                    .addGroup(header_panel_2Layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header_panel_2Layout.setVerticalGroup(
            header_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panel_2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(header_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(client_control_panel_label_2)
                    .addComponent(client_control_panel_label_1)
                    .addComponent(nav_icon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(header_panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(side_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(server_details_panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(server_details_panel_2, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(client_details_panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(client_details_panel_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(user_messaging_side_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addGap(2, 2, 2)
                                .addComponent(user_messaging_main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(user_messaging_top_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addComponent(footer_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(header_panel_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(header_panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(header_panel_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(client_details_panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(client_details_panel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(server_details_panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(server_details_panel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(user_messaging_top_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_messaging_side_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(user_messaging_main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addComponent(footer_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(side_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_messages_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_messages_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_messages_textfieldActionPerformed

    private void exit_app_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_app_labelMouseClicked

    }//GEN-LAST:event_exit_app_labelMouseClicked

    private void exit_app_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_app_labelMouseEntered

    }//GEN-LAST:event_exit_app_labelMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientUserMessaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientUserMessaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientUserMessaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientUserMessaging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientUserMessaging().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel client_control_panel_label_1;
    private javax.swing.JLabel client_control_panel_label_2;
    private javax.swing.JLabel client_details_ID_number_label;
    private javax.swing.JLabel client_details_IP_label;
    private javax.swing.JLabel client_details_icon;
    private javax.swing.JLabel client_details_label_1;
    private javax.swing.JLabel client_details_label_2;
    private javax.swing.JPanel client_details_panel_1;
    private javax.swing.JPanel client_details_panel_2;
    private javax.swing.JLabel client_details_port_label;
    private javax.swing.JLabel client_features_label;
    private javax.swing.JLabel discussionNet_title;
    private javax.swing.JLabel exit_app_label;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel footer_panel;
    private javax.swing.JLabel footer_text;
    private javax.swing.JPanel header_panel_1;
    private javax.swing.JPanel header_panel_2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel messages_label;
    private javax.swing.JLabel nav_icon;
    private javax.swing.JLabel right_arrow_icon_1;
    private javax.swing.JLabel right_arrow_icon_2;
    private javax.swing.JLabel right_arrow_icon_3;
    private javax.swing.JLabel right_arrow_icon_4;
    private javax.swing.JLabel right_arrow_icon_5;
    private javax.swing.JLabel server_details_icon;
    private javax.swing.JLabel server_details_label_1;
    private javax.swing.JLabel server_details_label_2;
    private javax.swing.JPanel server_details_panel_1;
    private javax.swing.JPanel server_details_panel_2;
    private javax.swing.JPanel side_panel;
    private javax.swing.JLabel update_logs_label;
    private javax.swing.JButton user_messages_send_button;
    private javax.swing.JTextField user_messages_textfield;
    private javax.swing.JLabel user_messaging_icon;
    private javax.swing.JLabel user_messaging_label;
    private javax.swing.JLabel user_messaging_label_1;
    private javax.swing.JLabel user_messaging_label_2;
    private javax.swing.JPanel user_messaging_main_panel;
    private javax.swing.JPanel user_messaging_side_panel;
    private javax.swing.JPanel user_messaging_top_panel;
    private javax.swing.JLabel users_label;
    // End of variables declaration//GEN-END:variables
}
