/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package work.universitycourse.comp1549;

/**
 *
 * @author Daniel Browne
 */
public class identitySetup extends javax.swing.JFrame {

    /**
     * Creates new form identitySetup
     */
    public identitySetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        main_image = new javax.swing.JLabel();
        identity_setup_title_part_1 = new javax.swing.JLabel();
        identity_setup_title_part_2 = new javax.swing.JLabel();
        assigned_ID_nuber_label = new javax.swing.JLabel();
        assigned_ID_number_textbox = new javax.swing.JTextField();
        server_IP_label = new javax.swing.JLabel();
        server_IP_textbox = new javax.swing.JTextField();
        server_port_label = new javax.swing.JLabel();
        server_port_textbox = new javax.swing.JTextField();
        authenticate_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(854, 519));
        setMinimumSize(new java.awt.Dimension(854, 519));
        setPreferredSize(new java.awt.Dimension(854, 519));
        setResizable(false);

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setMaximumSize(new java.awt.Dimension(854, 519));
        main_panel.setMinimumSize(new java.awt.Dimension(854, 519));
        main_panel.setName(""); // NOI18N
        main_panel.setPreferredSize(new java.awt.Dimension(854, 519));

        main_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Identify.png"))); // NOI18N

        identity_setup_title_part_1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        identity_setup_title_part_1.setForeground(new java.awt.Color(0, 36, 109));
        identity_setup_title_part_1.setText("DiscussionNet");

        identity_setup_title_part_2.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        identity_setup_title_part_2.setText("Identity Setup");

        assigned_ID_nuber_label.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        assigned_ID_nuber_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ID_Icon.png"))); // NOI18N
        assigned_ID_nuber_label.setText("Assigned ID Number");

        server_IP_label.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        server_IP_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configure_ip_icon.png"))); // NOI18N
        server_IP_label.setText("Server IP Address");

        server_IP_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                server_IP_textboxActionPerformed(evt);
            }
        });

        server_port_label.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        server_port_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/port_icon.png"))); // NOI18N
        server_port_label.setText("Server Port");

        server_port_textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                server_port_textboxActionPerformed(evt);
            }
        });

        authenticate_button.setBackground(new java.awt.Color(255, 255, 255));
        authenticate_button.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        authenticate_button.setForeground(new java.awt.Color(255, 255, 255));
        authenticate_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_button_background.png"))); // NOI18N
        authenticate_button.setText("Authenticate");
        authenticate_button.setBorder(null);
        authenticate_button.setBorderPainted(false);
        authenticate_button.setContentAreaFilled(false);
        authenticate_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(main_image)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(assigned_ID_nuber_label)
                            .addComponent(server_IP_label)
                            .addComponent(server_port_label)
                            .addGroup(main_panelLayout.createSequentialGroup()
                                .addComponent(identity_setup_title_part_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(identity_setup_title_part_2))
                            .addComponent(assigned_ID_number_textbox)
                            .addComponent(server_IP_textbox)
                            .addComponent(server_port_textbox)))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(authenticate_button)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(main_image))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(identity_setup_title_part_1)
                            .addComponent(identity_setup_title_part_2))
                        .addGap(18, 18, 18)
                        .addComponent(assigned_ID_nuber_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(assigned_ID_number_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(server_IP_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(server_IP_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(server_port_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(server_port_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(authenticate_button)))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void server_IP_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_server_IP_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_server_IP_textboxActionPerformed

    private void server_port_textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_server_port_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_server_port_textboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(identitySetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(identitySetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(identitySetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(identitySetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new identitySetup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assigned_ID_nuber_label;
    private javax.swing.JTextField assigned_ID_number_textbox;
    private javax.swing.JButton authenticate_button;
    private javax.swing.JLabel identity_setup_title_part_1;
    private javax.swing.JLabel identity_setup_title_part_2;
    private javax.swing.JLabel main_image;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel server_IP_label;
    private javax.swing.JTextField server_IP_textbox;
    private javax.swing.JLabel server_port_label;
    private javax.swing.JTextField server_port_textbox;
    // End of variables declaration//GEN-END:variables
}
