/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package work.universitycourse.comp1549;

/**
 *
  * @author Daniel Browne
 */
public class serverConnection extends javax.swing.JFrame {

    /**
     * Creates new form serverConnection
     */
    public serverConnection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        main_image = new javax.swing.JLabel();
        server_connection_title_part_1 = new javax.swing.JLabel();
        server_connection_title_part_2 = new javax.swing.JLabel();
        server_IP_address_label = new javax.swing.JLabel();
        server_IP_address_textbox = new javax.swing.JTextField();
        server_port_label = new javax.swing.JLabel();
        server_port_textbox = new javax.swing.JTextField();
        connect_to_server_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(854, 519));
        setMinimumSize(new java.awt.Dimension(854, 519));
        setPreferredSize(new java.awt.Dimension(854, 519));
        setResizable(false);

        main_panel.setBackground(new java.awt.Color(255, 255, 255));

        main_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connect.png"))); // NOI18N

        server_connection_title_part_1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        server_connection_title_part_1.setForeground(new java.awt.Color(0, 36, 109));
        server_connection_title_part_1.setText("DiscussionNet");

        server_connection_title_part_2.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        server_connection_title_part_2.setText("Server Connection");

        server_IP_address_label.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        server_IP_address_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configure_ip_icon.png"))); // NOI18N
        server_IP_address_label.setText("Server IP Address");

        server_port_label.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        server_port_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/port_icon.png"))); // NOI18N
        server_port_label.setText("Server Port");

        connect_to_server_button.setBackground(new java.awt.Color(255, 255, 255));
        connect_to_server_button.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        connect_to_server_button.setForeground(new java.awt.Color(255, 255, 255));
        connect_to_server_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_button_background.png"))); // NOI18N
        connect_to_server_button.setText("Connect to Server");
        connect_to_server_button.setBorder(null);
        connect_to_server_button.setBorderPainted(false);
        connect_to_server_button.setContentAreaFilled(false);
        connect_to_server_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        connect_to_server_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect_to_server_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(main_image)
                .addGap(69, 69, 69)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(server_port_label)
                        .addComponent(server_IP_address_label)
                        .addGroup(main_panelLayout.createSequentialGroup()
                            .addComponent(server_connection_title_part_1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(server_connection_title_part_2))
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(server_IP_address_textbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                            .addComponent(server_port_textbox, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addComponent(connect_to_server_button)
                        .addGap(48, 48, 48)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(server_connection_title_part_1)
                            .addComponent(server_connection_title_part_2))
                        .addGap(18, 18, 18)
                        .addComponent(server_IP_address_label)
                        .addGap(18, 18, 18)
                        .addComponent(server_IP_address_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(server_port_label)
                        .addGap(18, 18, 18)
                        .addComponent(server_port_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(connect_to_server_button))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(main_image)))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connect_to_server_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect_to_server_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connect_to_server_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(serverConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(serverConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(serverConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(serverConnection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new serverConnection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connect_to_server_button;
    private javax.swing.JLabel main_image;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel server_IP_address_label;
    private javax.swing.JTextField server_IP_address_textbox;
    private javax.swing.JLabel server_connection_title_part_1;
    private javax.swing.JLabel server_connection_title_part_2;
    private javax.swing.JLabel server_port_label;
    private javax.swing.JTextField server_port_textbox;
    // End of variables declaration//GEN-END:variables
}
