/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package work.universitycourse.comp1549;


import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Daniel Browne
 */
public class startupInterface extends javax.swing.JFrame {
    
    

    /**
     * Creates new form StartUpInterface
     */
    public startupInterface() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon img = new ImageIcon(getClass().getResource("/icon.png"));
        main_panel = new javax.swing.JPanel();
        existing_network_label = new javax.swing.JLabel();
        create_network_label = new javax.swing.JLabel();
        welcome_text_part_2 = new javax.swing.JLabel();
        welcome_text_part_3 = new javax.swing.JLabel();
        welcome_text_part_1 = new javax.swing.JLabel();
        footer_text = new javax.swing.JLabel();
        main_image = new javax.swing.JLabel();
        configure_server_button = new javax.swing.JButton();
        configure_client_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DiscussionNet V1.0 ");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(img.getImage());
        setMinimumSize(new java.awt.Dimension(854, 519));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        main_panel.setBackground(new java.awt.Color(255, 255, 255));

        existing_network_label.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        existing_network_label.setForeground(new java.awt.Color(47, 46, 65));
        existing_network_label.setText("I want to join an existing network...");

        create_network_label.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        create_network_label.setForeground(new java.awt.Color(47, 46, 65));
        create_network_label.setText("I want to create a new network...");

        welcome_text_part_2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        welcome_text_part_2.setForeground(new java.awt.Color(0, 36, 109));
        welcome_text_part_2.setText("DiscussionNet");

        welcome_text_part_3.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        welcome_text_part_3.setForeground(new java.awt.Color(47, 46, 65));
        welcome_text_part_3.setText("Initial Setup");

        welcome_text_part_1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        welcome_text_part_1.setForeground(new java.awt.Color(47, 46, 65));
        welcome_text_part_1.setText("Welcome To");

        footer_text.setFont(new java.awt.Font("Montserrat", 0, 9)); // NOI18N
        footer_text.setForeground(new java.awt.Color(47, 46, 65));
        footer_text.setText("DiscussionNet V1.0 - © Code Squad 2021 - Software Licenses");

        main_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/welcome_image.png"))); // NOI18N

        configure_server_button.setBackground(new java.awt.Color(255, 255, 255));
        configure_server_button.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        configure_server_button.setForeground(new java.awt.Color(255, 255, 255));
        configure_server_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_button_background.png"))); // NOI18N
        configure_server_button.setText("Configure Server");
        configure_server_button.setActionCommand("Configure Server");
        configure_server_button.setBorder(null);
        configure_server_button.setBorderPainted(false);
        configure_server_button.setContentAreaFilled(false);
        configure_server_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        configure_client_button.setBackground(new java.awt.Color(255, 255, 255));
        configure_client_button.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        configure_client_button.setForeground(new java.awt.Color(255, 255, 255));
        configure_client_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medium_button_background.png"))); // NOI18N
        configure_client_button.setText("Configure Client");
        configure_client_button.setBorder(null);
        configure_client_button.setBorderPainted(false);
        configure_client_button.setContentAreaFilled(false);
        configure_client_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(existing_network_label)
                .addGap(117, 117, 117)
                .addComponent(create_network_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(main_image))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(welcome_text_part_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcome_text_part_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcome_text_part_3))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(configure_client_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(configure_server_button)))
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(footer_text)
                .addGap(269, 269, 269))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(main_image)
                .addGap(18, 18, 18)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcome_text_part_1)
                    .addComponent(welcome_text_part_2)
                    .addComponent(welcome_text_part_3))
                .addGap(51, 51, 51)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existing_network_label)
                    .addComponent(create_network_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(configure_client_button)
                    .addComponent(configure_server_button))
                .addGap(86, 86, 86)
                .addComponent(footer_text)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startupInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startupInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startupInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startupInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
    
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startupInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configure_client_button;
    private javax.swing.JButton configure_server_button;
    private javax.swing.JLabel create_network_label;
    private javax.swing.JLabel existing_network_label;
    private javax.swing.JLabel footer_text;
    private javax.swing.JLabel main_image;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel welcome_text_part_1;
    private javax.swing.JLabel welcome_text_part_2;
    private javax.swing.JLabel welcome_text_part_3;
    // End of variables declaration//GEN-END:variables
}
