package work.universitycourse.comp1549.Interfaces.Client;

import static javax.swing.JOptionPane.showMessageDialog;
import work.universitycourse.comp1549.Components.RoundJTextField;
import work.universitycourse.comp1549.Interfaces.Licenses;
import work.universitycourse.comp1549.Modules.ClientManager;
import work.universitycourse.comp1549.Modules.InterfaceManager;

/**
 *
 * @author Adnan Turan
 * @author Daniel Browne
 * @author Gabriel Netz
 * @author William Phillips
 * 
 */
public class ClientIdentitySetup extends javax.swing.JFrame {
    // TODO: Compress into object - temp quick passing of variables.
    public static String serverIPAddress;
    public static String serverPort;
    
    /**
     * Creates new form identitySetup
     */
    public ClientIdentitySetup(String serverIPAddress, String serverPort) {
        super();
        this.serverIPAddress = serverIPAddress;
        this.serverPort = serverPort;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientIdentitySetupPanel = new javax.swing.JPanel();
        mainImage = new javax.swing.JLabel();
        discussionNetIdentitySetupLabel1 = new javax.swing.JLabel();
        discussionNetIdentitySetupLabel2 = new javax.swing.JLabel();
        assignedIDNumberLabel = new javax.swing.JLabel();
        assignedIDNumberTextfield = new RoundJTextField();
        clientIPAddressLabel = new javax.swing.JLabel();
        clientIPAddressTextField = new RoundJTextField();
        userMessagesIconLabel = new javax.swing.JLabel();
        clientPortLabel = new javax.swing.JLabel();
        clientPortTextField = new RoundJTextField();
        authenticateButton = new javax.swing.JButton();
        footerTextLabel = new javax.swing.JLabel();
        footerLicensesTextLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("work/universitycourse/comp1549/Interfaces/Client/Bundle"); // NOI18N
        setTitle(bundle.getString("ClientIdentitySetup.title")); // NOI18N
        setIconImage(InterfaceManager.programIcon.getImage());
        setMinimumSize(new java.awt.Dimension(854, 519));
        setName("DiscussionNet"); // NOI18N
        setResizable(false);

        clientIdentitySetupPanel.setBackground(new java.awt.Color(255, 255, 255));
        clientIdentitySetupPanel.setMaximumSize(new java.awt.Dimension(847, 519));
        clientIdentitySetupPanel.setMinimumSize(new java.awt.Dimension(847, 519));
        clientIdentitySetupPanel.setName(""); // NOI18N
        clientIdentitySetupPanel.setPreferredSize(new java.awt.Dimension(847, 519));
        InterfaceManager.detectExitRequest(clientIdentitySetupPanel);
        clientIdentitySetupPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientIdentitySetupPanelMouseClicked(evt);
            }
        });
        clientIdentitySetupPanel.setLayout(null);

        mainImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/identity.png"))); // NOI18N
        mainImage.setName("mainImage"); // NOI18N
        clientIdentitySetupPanel.add(mainImage);
        mainImage.setBounds(70, 159, 239, 207);

        discussionNetIdentitySetupLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        discussionNetIdentitySetupLabel1.setForeground(new java.awt.Color(0, 36, 109));
        discussionNetIdentitySetupLabel1.setText(bundle.getString("ClientIdentitySetup.discussionNetIdentitySetupLabel1.text_1")); // NOI18N
        discussionNetIdentitySetupLabel1.setName("discussionNetIdentitySetupLabel1"); // NOI18N
        clientIdentitySetupPanel.add(discussionNetIdentitySetupLabel1);
        discussionNetIdentitySetupLabel1.setBounds(426, 83, 175, 30);

        discussionNetIdentitySetupLabel2.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        discussionNetIdentitySetupLabel2.setText(bundle.getString("ClientIdentitySetup.discussionNetIdentitySetupLabel2.text_1")); // NOI18N
        discussionNetIdentitySetupLabel2.setName("discussionNetIdentitySetupLabel2"); // NOI18N
        clientIdentitySetupPanel.add(discussionNetIdentitySetupLabel2);
        discussionNetIdentitySetupLabel2.setBounds(607, 83, 171, 30);

        assignedIDNumberLabel.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        assignedIDNumberLabel.setForeground(new java.awt.Color(47, 46, 65));
        assignedIDNumberLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_id.png"))); // NOI18N
        assignedIDNumberLabel.setText(bundle.getString("ClientIdentitySetup.assignedIDNumberLabel.text_1")); // NOI18N
        assignedIDNumberLabel.setName("assignedIDNumberLabel"); // NOI18N
        clientIdentitySetupPanel.add(assignedIDNumberLabel);
        assignedIDNumberLabel.setBounds(426, 131, 153, 17);

        assignedIDNumberTextfield.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        assignedIDNumberTextfield.setForeground(new java.awt.Color(152, 150, 162));
        assignedIDNumberTextfield.setAlignmentX(0.0F);
        assignedIDNumberTextfield.setAlignmentY(0.0F);
        assignedIDNumberTextfield.setCaretColor(new java.awt.Color(152, 150, 162));
        assignedIDNumberTextfield.setDisabledTextColor(new java.awt.Color(152, 150, 162));
        assignedIDNumberTextfield.setMargin(new java.awt.Insets(0, 0, 0, 0));
        assignedIDNumberTextfield.setName("assignedIDNumberTextfield"); // NOI18N
        assignedIDNumberTextfield.setSelectionColor(new java.awt.Color(0, 63, 143));
        assignedIDNumberTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                assignedIDNumberTextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                assignedIDNumberTextfieldFocusLost(evt);
            }
        });
        clientIdentitySetupPanel.add(assignedIDNumberTextfield);
        assignedIDNumberTextfield.setBounds(426, 159, 343, 19);

        clientIPAddressLabel.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        clientIPAddressLabel.setForeground(new java.awt.Color(47, 46, 65));
        clientIPAddressLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wireless.png"))); // NOI18N
        clientIPAddressLabel.setText(bundle.getString("ClientIdentitySetup.clientIPAddressLabel.text_1")); // NOI18N
        clientIPAddressLabel.setName("clientIPAddressLabel"); // NOI18N
        clientIdentitySetupPanel.add(clientIPAddressLabel);
        clientIPAddressLabel.setBounds(426, 209, 127, 17);

        clientIPAddressTextField.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        clientIPAddressTextField.setForeground(new java.awt.Color(152, 150, 162));
        clientIPAddressTextField.setCaretColor(new java.awt.Color(152, 150, 162));
        clientIPAddressTextField.setDisabledTextColor(new java.awt.Color(152, 150, 162));
        clientIPAddressTextField.setMargin(new java.awt.Insets(0, 0, 0, 0));
        clientIPAddressTextField.setName("clientIPAddressTextField"); // NOI18N
        clientIPAddressTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clientIPAddressTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                clientIPAddressTextFieldFocusLost(evt);
            }
        });
        clientIdentitySetupPanel.add(clientIPAddressTextField);
        clientIPAddressTextField.setBounds(426, 237, 343, 19);

        userMessagesIconLabel.setBackground(new java.awt.Color(255, 255, 255));
        userMessagesIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        userMessagesIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userMessagesIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_icon.png"))); // NOI18N
        userMessagesIconLabel.setText(bundle.getString("ClientIdentitySetup.userMessagesIconLabel.text")); // NOI18N
        userMessagesIconLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userMessagesIconLabel.setFocusable(false);
        userMessagesIconLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userMessagesIconLabel.setIconTextGap(0);
        userMessagesIconLabel.setInheritsPopupMenu(false);
        userMessagesIconLabel.setName("userMessagesIconLabel"); // NOI18N
        userMessagesIconLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMessagesIconLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userMessagesIconLabelMouseEntered(evt);
            }
        });
        clientIdentitySetupPanel.add(userMessagesIconLabel);
        userMessagesIconLabel.setBounds(640, 370, 30, 30);

        clientPortLabel.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        clientPortLabel.setForeground(new java.awt.Color(47, 46, 65));
        clientPortLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/port_icon.png"))); // NOI18N
        clientPortLabel.setText(bundle.getString("ClientIdentitySetup.clientPortLabel.text_1")); // NOI18N
        clientPortLabel.setName("clientPortLabel"); // NOI18N
        clientIdentitySetupPanel.add(clientPortLabel);
        clientPortLabel.setBounds(426, 293, 86, 17);

        clientPortTextField.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        clientPortTextField.setForeground(new java.awt.Color(152, 150, 162));
        clientPortTextField.setCaretColor(new java.awt.Color(152, 150, 162));
        clientPortTextField.setDisabledTextColor(new java.awt.Color(152, 150, 162));
        clientPortTextField.setMargin(new java.awt.Insets(0, 0, 0, 0));
        clientPortTextField.setName("clientPortTextField"); // NOI18N
        clientPortTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clientPortTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                clientPortTextFieldFocusLost(evt);
            }
        });
        clientIdentitySetupPanel.add(clientPortTextField);
        clientPortTextField.setBounds(426, 321, 343, 19);

        authenticateButton.setBackground(new java.awt.Color(255, 255, 255));
        authenticateButton.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        authenticateButton.setForeground(new java.awt.Color(255, 255, 255));
        authenticateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/medium.png"))); // NOI18N
        authenticateButton.setText(bundle.getString("ClientIdentitySetup.authenticateButton.text_1")); // NOI18N
        authenticateButton.setBorder(null);
        authenticateButton.setBorderPainted(false);
        authenticateButton.setContentAreaFilled(false);
        authenticateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        authenticateButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        authenticateButton.setName("authenticateButton"); // NOI18N
        authenticateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                authenticateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                authenticateButtonMouseExited(evt);
            }
        });
        authenticateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenticateButtonActionPerformed(evt);
            }
        });
        clientIdentitySetupPanel.add(authenticateButton);
        authenticateButton.setBounds(430, 350, 343, 69);

        footerTextLabel.setFont(new java.awt.Font("Montserrat", 0, 9)); // NOI18N
        footerTextLabel.setForeground(new java.awt.Color(47, 46, 65));
        footerTextLabel.setText(bundle.getString("ClientIdentitySetup.footerTextLabel.text_1")); // NOI18N
        footerTextLabel.setName("footerTextLabel"); // NOI18N
        clientIdentitySetupPanel.add(footerTextLabel);
        footerTextLabel.setBounds(285, 507, 189, 12);

        footerLicensesTextLabel.setFont(new java.awt.Font("Montserrat", 2, 9)); // NOI18N
        footerLicensesTextLabel.setForeground(new java.awt.Color(47, 46, 65));
        footerLicensesTextLabel.setText(bundle.getString("ClientIdentitySetup.footerLicensesTextLabel.text")); // NOI18N
        footerLicensesTextLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        footerLicensesTextLabel.setName("footerLicensesTextLabel"); // NOI18N
        footerLicensesTextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                footerLicensesTextLabelMouseClicked(evt);
            }
        });
        clientIdentitySetupPanel.add(footerLicensesTextLabel);
        footerLicensesTextLabel.setBounds(480, 507, 80, 12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientIdentitySetupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientIdentitySetupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName(bundle.getString("ClientIdentitySetup.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void authenticateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenticateButtonActionPerformed
        confirmIdentity();
    }//GEN-LAST:event_authenticateButtonActionPerformed

    private void authenticateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authenticateButtonMouseEntered
        InterfaceManager.buttonHover(authenticateButton, true, "medium");
    }//GEN-LAST:event_authenticateButtonMouseEntered

    private void authenticateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authenticateButtonMouseExited
        InterfaceManager.buttonHover(authenticateButton, false, "medium");
    }//GEN-LAST:event_authenticateButtonMouseExited

    private void assignedIDNumberTextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_assignedIDNumberTextfieldFocusGained
        InterfaceManager.toggleTextFieldFocus(assignedIDNumberTextfield, true);
    }//GEN-LAST:event_assignedIDNumberTextfieldFocusGained

    private void assignedIDNumberTextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_assignedIDNumberTextfieldFocusLost
        InterfaceManager.toggleTextFieldFocus(assignedIDNumberTextfield, false);
    }//GEN-LAST:event_assignedIDNumberTextfieldFocusLost

    private void clientIPAddressTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientIPAddressTextFieldFocusGained
        InterfaceManager.toggleTextFieldFocus(clientIPAddressTextField, true);
    }//GEN-LAST:event_clientIPAddressTextFieldFocusGained

    private void clientIPAddressTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientIPAddressTextFieldFocusLost
        InterfaceManager.toggleTextFieldFocus(clientIPAddressTextField, false);
    }//GEN-LAST:event_clientIPAddressTextFieldFocusLost

    private void clientPortTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientPortTextFieldFocusGained
        InterfaceManager.toggleTextFieldFocus(clientPortTextField, true);
    }//GEN-LAST:event_clientPortTextFieldFocusGained

    private void clientPortTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientPortTextFieldFocusLost
        InterfaceManager.toggleTextFieldFocus(clientPortTextField, false);
    }//GEN-LAST:event_clientPortTextFieldFocusLost

    private void clientIdentitySetupPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientIdentitySetupPanelMouseClicked
        InterfaceManager.toggleTextFieldFocus(assignedIDNumberTextfield, false);
        InterfaceManager.toggleTextFieldFocus(clientIPAddressTextField, false);
        InterfaceManager.toggleTextFieldFocus(clientPortTextField, false);
    }//GEN-LAST:event_clientIdentitySetupPanelMouseClicked

    private void userMessagesIconLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMessagesIconLabelMouseClicked
        confirmIdentity();
    }//GEN-LAST:event_userMessagesIconLabelMouseClicked

    private void userMessagesIconLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMessagesIconLabelMouseEntered
        InterfaceManager.buttonHover(authenticateButton, true, "medium");
    }//GEN-LAST:event_userMessagesIconLabelMouseEntered

    private void footerLicensesTextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footerLicensesTextLabelMouseClicked
        InterfaceManager.changeWindow(this, new Licenses());
    }//GEN-LAST:event_footerLicensesTextLabelMouseClicked

    private void confirmIdentity() {
        InterfaceManager.changeWindow(
            this,
            new ClientMessaging(
                this.serverIPAddress,
                this.serverPort,
                assignedIDNumberTextfield.getText(),
                clientIPAddressTextField.getText(),
                clientPortTextField.getText()
            )
        );
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientIdentitySetup.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientIdentitySetup(args[0], args[1]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assignedIDNumberLabel;
    private javax.swing.JTextField assignedIDNumberTextfield;
    private javax.swing.JButton authenticateButton;
    private javax.swing.JLabel clientIPAddressLabel;
    private javax.swing.JTextField clientIPAddressTextField;
    private javax.swing.JPanel clientIdentitySetupPanel;
    private javax.swing.JLabel clientPortLabel;
    private javax.swing.JTextField clientPortTextField;
    private javax.swing.JLabel discussionNetIdentitySetupLabel1;
    private javax.swing.JLabel discussionNetIdentitySetupLabel2;
    private javax.swing.JLabel footerLicensesTextLabel;
    private javax.swing.JLabel footerTextLabel;
    private javax.swing.JLabel mainImage;
    private javax.swing.JLabel userMessagesIconLabel;
    // End of variables declaration//GEN-END:variables
}
