package work.universitycourse.comp1549.Interfaces.Client;

import work.universitycourse.comp1549.Components.Message;
import work.universitycourse.comp1549.Components.RoundJTextField;
import work.universitycourse.comp1549.Interfaces.Licenses;
import work.universitycourse.comp1549.Modules.ClientManager;
import work.universitycourse.comp1549.Modules.InterfaceManager;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Adnan Turan
 * @author Daniel Browne
 * @author Gabriel Netz
 * @author William Phillips
 * 
 */
public class ClientMessaging extends javax.swing.JFrame {
    // TODO: Compress into object - temp quick passing of variables.
    public static String serverIPAddress;
    public static String serverPort;
    public static String clientIdentifier;
    public static String clientIPAddress;
    public static String clientPort;
    
    private static ClientManager client;
    private static ClientManager listener;


    /**
     * Creates new form clientUserMessaging
     */
    public ClientMessaging(String serverIPAddress, String serverPort, String clientIdentifier, String clientIPAddress, String clientPort) {
        super();
        this.serverIPAddress = serverIPAddress;
        this.serverPort = serverPort;
        this.clientIdentifier = clientIdentifier;
        this.clientIPAddress = clientIPAddress;
        this.clientPort = clientPort;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        headerNamePanel = new javax.swing.JPanel();
        discussionNetLabel = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        clientFeaturesLabel = new javax.swing.JLabel();
        userMessagingLabel = new javax.swing.JLabel();
        updateLogsLabel = new javax.swing.JLabel();
        exitApplicationLabel = new javax.swing.JLabel();
        clientDetailsPanel1 = new javax.swing.JPanel();
        clientDetailsIcon = new javax.swing.JLabel();
        clientDetailsLabel1 = new javax.swing.JLabel();
        clientDetailsLabel2 = new javax.swing.JLabel();
        serverDetailsPanel1 = new javax.swing.JPanel();
        server_details_icon = new javax.swing.JLabel();
        serverDetailsLabel1 = new javax.swing.JLabel();
        serverDetailsLabel2 = new javax.swing.JLabel();
        footerPanel = new javax.swing.JPanel();
        footerTextLabel = new javax.swing.JLabel();
        footerLicensesTextLabel = new javax.swing.JLabel();
        userMessagingTopPanel = new javax.swing.JPanel();
        userMessagingIconLabel = new javax.swing.JLabel();
        userMessagingLabel1 = new javax.swing.JLabel();
        userMessagingLabel2 = new javax.swing.JLabel();
        userMessagingSidePanel = new javax.swing.JPanel();
        usersLabel = new javax.swing.JLabel();
        userLabel1 = new javax.swing.JLabel();
        rightArrowIcon1 = new javax.swing.JLabel();
        userLabel2 = new javax.swing.JLabel();
        userLabel3 = new javax.swing.JLabel();
        userLabel4 = new javax.swing.JLabel();
        userLabel5 = new javax.swing.JLabel();
        rightArrowIcon2 = new javax.swing.JLabel();
        rightArrowIcon3 = new javax.swing.JLabel();
        rightArrowIcon4 = new javax.swing.JLabel();
        rightArrowIcon5 = new javax.swing.JLabel();
        temporaryStartListenerButton = new javax.swing.JButton();
        temporaryStartClientButton = new javax.swing.JButton();
        startExampleOneButton = new javax.swing.JButton();
        userMessagingMainPanel = new javax.swing.JPanel();
        userMessagesTextfield = new RoundJTextField();
        messagesLabel = new javax.swing.JLabel();
        temporarySenderIdentifierTextBox = new javax.swing.JTextField();
        startExampleTwoButton = new javax.swing.JButton();
        startExampleThreeButton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        userMessagesIconLabel = new javax.swing.JLabel();
        userMessagesButton = new javax.swing.JButton();
        clientDetailsPanel2 = new javax.swing.JPanel();
        clientDetailsIPAddressLabel = new javax.swing.JLabel();
        clientDetailsIPAddressValueLabel = new javax.swing.JLabel();
        clientDetailsConnectionPortLabel = new javax.swing.JLabel();
        clientDetailsConnectionPortValueLabel = new javax.swing.JLabel();
        clientDetailsAssignedIDNumberLabel = new javax.swing.JLabel();
        clientDetailsAssignedIDNumberValueLabel = new javax.swing.JLabel();
        serverDetailsPanel2 = new javax.swing.JPanel();
        serverDetailsIPAddressLabel = new javax.swing.JLabel();
        serverDetailsIPAddressValueLabel = new javax.swing.JLabel();
        serverDetailsConnectionPortLabel = new javax.swing.JLabel();
        serverDetailsConnectionPortValueLabel = new javax.swing.JLabel();
        serverDetailsConnectionStatusLabel = new javax.swing.JLabel();
        serverDetailsConnectionStatusValueLabel = new javax.swing.JLabel();
        headerTitlePanel = new javax.swing.JPanel();
        navIconLabel = new javax.swing.JLabel();
        clientControlPanelLabel2 = new javax.swing.JLabel();
        clientControlPanelLabel1 = new javax.swing.JLabel();

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/black_arrow.png"))); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("work/universitycourse/comp1549/Interfaces/Client/Bundle"); // NOI18N
        setTitle(bundle.getString("ClientMessaging.title")); // NOI18N
        setBackground(new java.awt.Color(242, 244, 250));
        setIconImage(InterfaceManager.programIcon.getImage());
        setMinimumSize(new java.awt.Dimension(1090, 708));
        setName("DiscussionNet"); // NOI18N
        setResizable(false);

        headerNamePanel.setBackground(new java.awt.Color(255, 255, 255));
        headerNamePanel.setName("headerNamePanel"); // NOI18N
        headerNamePanel.setPreferredSize(new java.awt.Dimension(153, 43));
        InterfaceManager.detectExitRequest(headerNamePanel);

        discussionNetLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        discussionNetLabel.setForeground(new java.awt.Color(0, 36, 109));
        discussionNetLabel.setText(bundle.getString("ClientMessaging.discussionNetLabel.text_1")); // NOI18N
        discussionNetLabel.setName("discussionNetLabel"); // NOI18N

        javax.swing.GroupLayout headerNamePanelLayout = new javax.swing.GroupLayout(headerNamePanel);
        headerNamePanel.setLayout(headerNamePanelLayout);
        headerNamePanelLayout.setHorizontalGroup(
            headerNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerNamePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(discussionNetLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        headerNamePanelLayout.setVerticalGroup(
            headerNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerNamePanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(discussionNetLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        sidePanel.setBackground(new java.awt.Color(0, 36, 109));
        sidePanel.setForeground(new java.awt.Color(0, 36, 109));
        sidePanel.setToolTipText(bundle.getString("ClientMessaging.sidePanel.toolTipText_1")); // NOI18N
        sidePanel.setName("sidePanel"); // NOI18N
        sidePanel.setPreferredSize(new java.awt.Dimension(154, 60));

        clientFeaturesLabel.setBackground(new java.awt.Color(255, 255, 255));
        clientFeaturesLabel.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientFeaturesLabel.setForeground(new java.awt.Color(255, 255, 255));
        clientFeaturesLabel.setText(bundle.getString("ClientMessaging.clientFeaturesLabel.text_1")); // NOI18N
        clientFeaturesLabel.setName("clientFeaturesLabel"); // NOI18N

        userMessagingLabel.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        userMessagingLabel.setForeground(new java.awt.Color(255, 255, 255));
        userMessagingLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mail.png"))); // NOI18N
        userMessagingLabel.setText(bundle.getString("ClientMessaging.userMessagingLabel.text_1")); // NOI18N
        userMessagingLabel.setName("userMessagingLabel"); // NOI18N

        updateLogsLabel.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        updateLogsLabel.setForeground(new java.awt.Color(255, 255, 255));
        updateLogsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/file_icon.png"))); // NOI18N
        updateLogsLabel.setText(bundle.getString("ClientMessaging.updateLogsLabel.text_1")); // NOI18N
        updateLogsLabel.setName("updateLogsLabel"); // NOI18N

        exitApplicationLabel.setBackground(new java.awt.Color(255, 255, 255));
        exitApplicationLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        exitApplicationLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitApplicationLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        exitApplicationLabel.setText(bundle.getString("ClientMessaging.exitApplicationLabel.text_1")); // NOI18N
        exitApplicationLabel.setName("exitApplicationLabel"); // NOI18N

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateLogsLabel)
                    .addComponent(userMessagingLabel)
                    .addComponent(clientFeaturesLabel)
                    .addComponent(exitApplicationLabel))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(clientFeaturesLabel)
                .addGap(18, 18, 18)
                .addComponent(userMessagingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateLogsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitApplicationLabel)
                .addGap(28, 28, 28))
        );

        clientDetailsPanel1.setBackground(new java.awt.Color(255, 255, 255));
        clientDetailsPanel1.setName("clientDetailsPanel1"); // NOI18N
        clientDetailsPanel1.setPreferredSize(new java.awt.Dimension(322, 100));

        clientDetailsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/client_details.png"))); // NOI18N
        clientDetailsIcon.setName("clientDetailsIcon"); // NOI18N

        clientDetailsLabel1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        clientDetailsLabel1.setText(bundle.getString("ClientMessaging.clientDetailsLabel1.text_1")); // NOI18N
        clientDetailsLabel1.setName("clientDetailsLabel1"); // NOI18N

        clientDetailsLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        clientDetailsLabel2.setForeground(new java.awt.Color(0, 36, 109));
        clientDetailsLabel2.setText(bundle.getString("ClientMessaging.clientDetailsLabel2.text_1")); // NOI18N
        clientDetailsLabel2.setName("clientDetailsLabel2"); // NOI18N

        javax.swing.GroupLayout clientDetailsPanel1Layout = new javax.swing.GroupLayout(clientDetailsPanel1);
        clientDetailsPanel1.setLayout(clientDetailsPanel1Layout);
        clientDetailsPanel1Layout.setHorizontalGroup(
            clientDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(clientDetailsIcon)
                .addGap(37, 37, 37)
                .addComponent(clientDetailsLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientDetailsLabel2)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        clientDetailsPanel1Layout.setVerticalGroup(
            clientDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(clientDetailsIcon)
                .addGap(22, 22, 22))
            .addGroup(clientDetailsPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(clientDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientDetailsLabel1)
                    .addComponent(clientDetailsLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        serverDetailsPanel1.setBackground(new java.awt.Color(255, 255, 255));
        serverDetailsPanel1.setName("serverDetailsPanel1"); // NOI18N
        serverDetailsPanel1.setPreferredSize(new java.awt.Dimension(322, 100));

        server_details_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/server_details.png"))); // NOI18N
        server_details_icon.setName("server_details_icon"); // NOI18N

        serverDetailsLabel1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        serverDetailsLabel1.setText(bundle.getString("ClientMessaging.serverDetailsLabel1.text_1")); // NOI18N
        serverDetailsLabel1.setName("serverDetailsLabel1"); // NOI18N

        serverDetailsLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        serverDetailsLabel2.setForeground(new java.awt.Color(0, 36, 109));
        serverDetailsLabel2.setText(bundle.getString("ClientMessaging.serverDetailsLabel2.text_1")); // NOI18N
        serverDetailsLabel2.setName("serverDetailsLabel2"); // NOI18N

        javax.swing.GroupLayout serverDetailsPanel1Layout = new javax.swing.GroupLayout(serverDetailsPanel1);
        serverDetailsPanel1.setLayout(serverDetailsPanel1Layout);
        serverDetailsPanel1Layout.setHorizontalGroup(
            serverDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serverDetailsPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(server_details_icon)
                .addGap(39, 39, 39)
                .addComponent(serverDetailsLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serverDetailsLabel2)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        serverDetailsPanel1Layout.setVerticalGroup(
            serverDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serverDetailsPanel1Layout.createSequentialGroup()
                .addGroup(serverDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(serverDetailsPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(server_details_icon))
                    .addGroup(serverDetailsPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(serverDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serverDetailsLabel1)
                            .addComponent(serverDetailsLabel2))))
                .addContainerGap())
        );

        footerPanel.setBackground(new java.awt.Color(255, 255, 255));
        footerPanel.setName("footerPanel"); // NOI18N
        footerPanel.setPreferredSize(new java.awt.Dimension(936, 20));

        footerTextLabel.setFont(new java.awt.Font("Montserrat", 0, 9)); // NOI18N
        footerTextLabel.setForeground(new java.awt.Color(47, 46, 65));
        footerTextLabel.setText(bundle.getString("ClientMessaging.footerTextLabel.text_1")); // NOI18N
        footerTextLabel.setName("footerTextLabel"); // NOI18N

        footerLicensesTextLabel.setFont(new java.awt.Font("Montserrat", 2, 9)); // NOI18N
        footerLicensesTextLabel.setForeground(new java.awt.Color(47, 46, 65));
        footerLicensesTextLabel.setText(bundle.getString("ClientMessaging.footerLicensesTextLabel.text")); // NOI18N
        footerLicensesTextLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        footerLicensesTextLabel.setName("footerLicensesTextLabel"); // NOI18N
        footerLicensesTextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                footerLicensesTextLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(footerTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footerLicensesTextLabel)
                .addGap(328, 328, 328))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(footerLicensesTextLabel)
                    .addComponent(footerTextLabel))
                .addContainerGap())
        );

        userMessagingTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        userMessagingTopPanel.setMinimumSize(new java.awt.Dimension(93, 100));
        userMessagingTopPanel.setName("userMessagingTopPanel"); // NOI18N
        userMessagingTopPanel.setPreferredSize(new java.awt.Dimension(894, 93));

        userMessagingIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/user_messaging.png"))); // NOI18N
        userMessagingIconLabel.setName("userMessagingIconLabel"); // NOI18N

        userMessagingLabel1.setFont(new java.awt.Font("Montserrat", 0, 28)); // NOI18N
        userMessagingLabel1.setText(bundle.getString("ClientMessaging.userMessagingLabel1.text_1")); // NOI18N
        userMessagingLabel1.setName("userMessagingLabel1"); // NOI18N

        userMessagingLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 28)); // NOI18N
        userMessagingLabel2.setForeground(new java.awt.Color(0, 36, 109));
        userMessagingLabel2.setText(bundle.getString("ClientMessaging.userMessagingLabel2.text_1")); // NOI18N
        userMessagingLabel2.setName("userMessagingLabel2"); // NOI18N

        javax.swing.GroupLayout userMessagingTopPanelLayout = new javax.swing.GroupLayout(userMessagingTopPanel);
        userMessagingTopPanel.setLayout(userMessagingTopPanelLayout);
        userMessagingTopPanelLayout.setHorizontalGroup(
            userMessagingTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMessagingTopPanelLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(userMessagingIconLabel)
                .addGap(18, 18, 18)
                .addComponent(userMessagingLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userMessagingLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userMessagingTopPanelLayout.setVerticalGroup(
            userMessagingTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMessagingTopPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(userMessagingTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userMessagingIconLabel)
                    .addGroup(userMessagingTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userMessagingLabel2)
                        .addComponent(userMessagingLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userMessagingSidePanel.setBackground(new java.awt.Color(255, 255, 255));
        userMessagingSidePanel.setName("userMessagingSidePanel"); // NOI18N
        userMessagingSidePanel.setPreferredSize(new java.awt.Dimension(156, 298));

        usersLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        usersLabel.setText(bundle.getString("ClientMessaging.usersLabel.text_1")); // NOI18N
        usersLabel.setName("usersLabel"); // NOI18N

        userLabel1.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        userLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel1.setText(bundle.getString("ClientMessaging.userLabel1.text_1")); // NOI18N
        userLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        userLabel1.setName("userLabel1"); // NOI18N

        rightArrowIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/black_arrow.png"))); // NOI18N
        rightArrowIcon1.setName("rightArrowIcon1"); // NOI18N

        userLabel2.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        userLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel2.setText(bundle.getString("ClientMessaging.userLabel2.text_1")); // NOI18N
        userLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        userLabel2.setName("userLabel2"); // NOI18N

        userLabel3.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        userLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel3.setText(bundle.getString("ClientMessaging.userLabel3.text_1")); // NOI18N
        userLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        userLabel3.setName("userLabel3"); // NOI18N

        userLabel4.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        userLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel4.setText(bundle.getString("ClientMessaging.userLabel4.text_1")); // NOI18N
        userLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        userLabel4.setName("userLabel4"); // NOI18N

        userLabel5.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        userLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel5.setText(bundle.getString("ClientMessaging.userLabel5.text_1")); // NOI18N
        userLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        userLabel5.setName("userLabel5"); // NOI18N

        rightArrowIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/black_arrow.png"))); // NOI18N
        rightArrowIcon2.setName("rightArrowIcon2"); // NOI18N

        rightArrowIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/black_arrow.png"))); // NOI18N
        rightArrowIcon3.setName("rightArrowIcon3"); // NOI18N

        rightArrowIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/black_arrow.png"))); // NOI18N
        rightArrowIcon4.setName("rightArrowIcon4"); // NOI18N

        rightArrowIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/black_arrow.png"))); // NOI18N
        rightArrowIcon5.setName("rightArrowIcon5"); // NOI18N

        temporaryStartListenerButton.setText(bundle.getString("ClientMessaging.temporaryStartListenerButton.text")); // NOI18N
        temporaryStartListenerButton.setName("temporaryStartListenerButton"); // NOI18N
        temporaryStartListenerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temporaryStartListenerButtonActionPerformed(evt);
            }
        });

        temporaryStartClientButton.setText(bundle.getString("ClientMessaging.temporaryStartClientButton.text")); // NOI18N
        temporaryStartClientButton.setName("temporaryStartClientButton"); // NOI18N
        temporaryStartClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temporaryStartClientButtonActionPerformed(evt);
            }
        });

        startExampleOneButton.setText(bundle.getString("ClientMessaging.startExampleOneButton.text")); // NOI18N
        startExampleOneButton.setName("startExampleOneButton"); // NOI18N
        startExampleOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startExampleOneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userMessagingSidePanelLayout = new javax.swing.GroupLayout(userMessagingSidePanel);
        userMessagingSidePanel.setLayout(userMessagingSidePanelLayout);
        userMessagingSidePanelLayout.setHorizontalGroup(
            userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                        .addComponent(userLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(rightArrowIcon1))
                    .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                        .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userLabel5)
                            .addComponent(userLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rightArrowIcon3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rightArrowIcon5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMessagingSidePanelLayout.createSequentialGroup()
                        .addComponent(userLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rightArrowIcon2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMessagingSidePanelLayout.createSequentialGroup()
                        .addComponent(userLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rightArrowIcon4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMessagingSidePanelLayout.createSequentialGroup()
                        .addComponent(temporaryStartClientButton)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(usersLabel)
                        .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(temporaryStartListenerButton)
                                .addComponent(startExampleOneButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))))
                .addGap(27, 27, 27))
        );
        userMessagingSidePanelLayout.setVerticalGroup(
            userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userMessagingSidePanelLayout.createSequentialGroup()
                        .addComponent(usersLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userLabel1))
                    .addComponent(rightArrowIcon1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userLabel2)
                    .addComponent(rightArrowIcon2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userLabel3)
                    .addComponent(rightArrowIcon3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rightArrowIcon4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userMessagingSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userLabel5)
                    .addComponent(rightArrowIcon5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(temporaryStartClientButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temporaryStartListenerButton)
                .addGap(18, 18, 18)
                .addComponent(startExampleOneButton)
                .addGap(31, 31, 31))
        );

        userMessagingMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        userMessagingMainPanel.setName("userMessagingMainPanel"); // NOI18N
        userMessagingMainPanel.setPreferredSize(new java.awt.Dimension(737, 298));
        userMessagingMainPanel.setLayout(null);

        userMessagesTextfield.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        userMessagesTextfield.setForeground(new java.awt.Color(152, 150, 162));
        userMessagesTextfield.setCaretColor(new java.awt.Color(152, 150, 162));
        userMessagesTextfield.setDisabledTextColor(new java.awt.Color(152, 150, 162));
        userMessagesTextfield.setName("userMessagesTextfield"); // NOI18N
        userMessagesTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userMessagesTextfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userMessagesTextfieldFocusLost(evt);
            }
        });
        userMessagingMainPanel.add(userMessagesTextfield);
        userMessagesTextfield.setBounds(25, 301, 559, 44);

        messagesLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        messagesLabel.setText(bundle.getString("ClientMessaging.messagesLabel.text_1")); // NOI18N
        messagesLabel.setName("messagesLabel"); // NOI18N
        userMessagingMainPanel.add(messagesLabel);
        messagesLabel.setBounds(25, 22, 58, 14);

        temporarySenderIdentifierTextBox.setText(bundle.getString("ClientMessaging.temporarySenderIdentifierTextBox.text")); // NOI18N
        temporarySenderIdentifierTextBox.setName("temporarySenderIdentifierTextBox"); // NOI18N

        startExampleTwoButton.setText(bundle.getString("ClientMessaging.startExampleTwoButton.text")); // NOI18N
        startExampleTwoButton.setName("startExampleTwoButton"); // NOI18N
        startExampleTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startExampleTwoButtonActionPerformed(evt);
            }
        });

        startExampleThreeButton.setText(bundle.getString("ClientMessaging.startExampleThreeButton.text")); // NOI18N
        startExampleThreeButton.setName("startExampleThreeButton"); // NOI18N
        startExampleThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startExampleThreeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userMessagingMainPanelLayout = new javax.swing.GroupLayout(userMessagingMainPanel);
        userMessagingMainPanel.setLayout(userMessagingMainPanelLayout);
        userMessagingMainPanelLayout.setHorizontalGroup(
            userMessagingMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMessagingMainPanelLayout.createSequentialGroup()
                .addGroup(userMessagingMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userMessagingMainPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(userMessagingMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messagesLabel)
                            .addGroup(userMessagingMainPanelLayout.createSequentialGroup()
                                .addGroup(userMessagingMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userMessagesTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(temporarySenderIdentifierTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userMessagesButton))))
                    .addGroup(userMessagingMainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(startExampleTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userMessagingMainPanelLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(startExampleThreeButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userMessagingMainPanelLayout.setVerticalGroup(
            userMessagingMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMessagingMainPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(messagesLabel)
                .addGap(95, 95, 95)
                .addComponent(startExampleThreeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startExampleTwoButton)
                .addGap(65, 65, 65)
                .addGroup(userMessagingMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMessagingMainPanelLayout.createSequentialGroup()
                        .addComponent(userMessagesButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMessagingMainPanelLayout.createSequentialGroup()
                        .addComponent(temporarySenderIdentifierTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userMessagesTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        userMessagingMainPanel.add(jLayeredPane1);
        jLayeredPane1.setBounds(581, 137, 100, 100);

        userMessagesIconLabel.setBackground(new java.awt.Color(255, 255, 255));
        userMessagesIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        userMessagesIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userMessagesIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_circle_icon.png"))); // NOI18N
        userMessagesIconLabel.setText(bundle.getString("ClientMessaging.userMessagesIconLabel.text")); // NOI18N
        userMessagesIconLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userMessagesIconLabel.setFocusable(false);
        userMessagesIconLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userMessagesIconLabel.setIconTextGap(0);
        userMessagesIconLabel.setInheritsPopupMenu(false);
        userMessagesIconLabel.setName("userMessagesIconLabel"); // NOI18N
        userMessagesIconLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMessagesIconLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userMessagesIconLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userMessagesIconLabelMouseExited(evt);
            }
        });
        userMessagingMainPanel.add(userMessagesIconLabel);
        userMessagesIconLabel.setBounds(600, 300, 120, 40);

        userMessagesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/small.png"))); // NOI18N
        userMessagesButton.setBorder(null);
        userMessagesButton.setContentAreaFilled(false);
        userMessagesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userMessagesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userMessagesButton.setName("userMessagesButton"); // NOI18N
        userMessagingMainPanel.add(userMessagesButton);
        userMessagesButton.setBounds(590, 290, 140, 60);

        clientDetailsPanel2.setBackground(new java.awt.Color(255, 255, 255));
        clientDetailsPanel2.setMinimumSize(new java.awt.Dimension(322, 92));
        clientDetailsPanel2.setName("clientDetailsPanel2"); // NOI18N

        clientDetailsIPAddressLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        clientDetailsIPAddressLabel.setText(bundle.getString("ClientMessaging.clientDetailsIPAddressLabel.text_1")); // NOI18N
        clientDetailsIPAddressLabel.setName("clientDetailsIPAddressLabel"); // NOI18N

        clientDetailsIPAddressValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        clientDetailsIPAddressValueLabel.setText(bundle.getString("ClientMessaging.clientDetailsIPAddressValueLabel.text_1")); // NOI18N
        clientDetailsIPAddressValueLabel.setName("clientDetailsIPAddressValueLabel"); // NOI18N

        clientDetailsConnectionPortLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        clientDetailsConnectionPortLabel.setText(bundle.getString("ClientMessaging.clientDetailsConnectionPortLabel.text_1")); // NOI18N
        clientDetailsConnectionPortLabel.setName("clientDetailsConnectionPortLabel"); // NOI18N

        clientDetailsConnectionPortValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        clientDetailsConnectionPortValueLabel.setText(bundle.getString("ClientMessaging.clientDetailsConnectionPortValueLabel.text_1")); // NOI18N
        clientDetailsConnectionPortValueLabel.setName("clientDetailsConnectionPortValueLabel"); // NOI18N

        clientDetailsAssignedIDNumberLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        clientDetailsAssignedIDNumberLabel.setText(bundle.getString("ClientMessaging.clientDetailsAssignedIDNumberLabel.text_1")); // NOI18N
        clientDetailsAssignedIDNumberLabel.setName("clientDetailsAssignedIDNumberLabel"); // NOI18N

        clientDetailsAssignedIDNumberValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        clientDetailsAssignedIDNumberValueLabel.setForeground(new java.awt.Color(112, 161, 255));
        clientDetailsAssignedIDNumberValueLabel.setText(bundle.getString("ClientMessaging.clientDetailsAssignedIDNumberValueLabel.text_1")); // NOI18N
        clientDetailsAssignedIDNumberValueLabel.setName("clientDetailsAssignedIDNumberValueLabel"); // NOI18N

        javax.swing.GroupLayout clientDetailsPanel2Layout = new javax.swing.GroupLayout(clientDetailsPanel2);
        clientDetailsPanel2.setLayout(clientDetailsPanel2Layout);
        clientDetailsPanel2Layout.setHorizontalGroup(
            clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientDetailsIPAddressLabel)
                    .addComponent(clientDetailsIPAddressValueLabel))
                .addGap(52, 52, 52)
                .addGroup(clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientDetailsConnectionPortLabel)
                    .addComponent(clientDetailsConnectionPortValueLabel))
                .addGap(45, 45, 45)
                .addGroup(clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientDetailsAssignedIDNumberValueLabel)
                    .addComponent(clientDetailsAssignedIDNumberLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clientDetailsPanel2Layout.setVerticalGroup(
            clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientDetailsPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientDetailsIPAddressLabel)
                    .addComponent(clientDetailsConnectionPortLabel)
                    .addComponent(clientDetailsAssignedIDNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clientDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientDetailsIPAddressValueLabel)
                    .addComponent(clientDetailsConnectionPortValueLabel)
                    .addComponent(clientDetailsAssignedIDNumberValueLabel))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        serverDetailsPanel2.setBackground(new java.awt.Color(255, 255, 255));
        serverDetailsPanel2.setName("serverDetailsPanel2"); // NOI18N
        serverDetailsPanel2.setPreferredSize(new java.awt.Dimension(322, 92));

        serverDetailsIPAddressLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        serverDetailsIPAddressLabel.setText(bundle.getString("ClientMessaging.serverDetailsIPAddressLabel.text_1")); // NOI18N
        serverDetailsIPAddressLabel.setName("serverDetailsIPAddressLabel"); // NOI18N

        serverDetailsIPAddressValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        serverDetailsIPAddressValueLabel.setText(bundle.getString("ClientMessaging.serverDetailsIPAddressValueLabel.text_1")); // NOI18N
        serverDetailsIPAddressValueLabel.setName("serverDetailsIPAddressValueLabel"); // NOI18N

        serverDetailsConnectionPortLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        serverDetailsConnectionPortLabel.setText(bundle.getString("ClientMessaging.serverDetailsConnectionPortLabel.text_1")); // NOI18N
        serverDetailsConnectionPortLabel.setName("serverDetailsConnectionPortLabel"); // NOI18N

        serverDetailsConnectionPortValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        serverDetailsConnectionPortValueLabel.setText(bundle.getString("ClientMessaging.serverDetailsConnectionPortValueLabel.text_1")); // NOI18N
        serverDetailsConnectionPortValueLabel.setName("serverDetailsConnectionPortValueLabel"); // NOI18N

        serverDetailsConnectionStatusLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 11)); // NOI18N
        serverDetailsConnectionStatusLabel.setText(bundle.getString("ClientMessaging.serverDetailsConnectionStatusLabel.text_1")); // NOI18N
        serverDetailsConnectionStatusLabel.setName("serverDetailsConnectionStatusLabel"); // NOI18N

        serverDetailsConnectionStatusValueLabel.setFont(new java.awt.Font("Montserrat Light", 0, 11)); // NOI18N
        serverDetailsConnectionStatusValueLabel.setForeground(new java.awt.Color(46, 213, 116));
        serverDetailsConnectionStatusValueLabel.setText(bundle.getString("ClientMessaging.serverDetailsConnectionStatusValueLabel.text_1")); // NOI18N
        serverDetailsConnectionStatusValueLabel.setName("serverDetailsConnectionStatusValueLabel"); // NOI18N

        javax.swing.GroupLayout serverDetailsPanel2Layout = new javax.swing.GroupLayout(serverDetailsPanel2);
        serverDetailsPanel2.setLayout(serverDetailsPanel2Layout);
        serverDetailsPanel2Layout.setHorizontalGroup(
            serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serverDetailsPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverDetailsIPAddressLabel)
                    .addComponent(serverDetailsIPAddressValueLabel))
                .addGap(50, 50, 50)
                .addGroup(serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverDetailsConnectionPortLabel)
                    .addComponent(serverDetailsConnectionPortValueLabel))
                .addGap(48, 48, 48)
                .addGroup(serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverDetailsConnectionStatusValueLabel)
                    .addComponent(serverDetailsConnectionStatusLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        serverDetailsPanel2Layout.setVerticalGroup(
            serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serverDetailsPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverDetailsIPAddressLabel)
                    .addComponent(serverDetailsConnectionPortLabel)
                    .addComponent(serverDetailsConnectionStatusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(serverDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverDetailsIPAddressValueLabel)
                    .addComponent(serverDetailsConnectionPortValueLabel)
                    .addComponent(serverDetailsConnectionStatusValueLabel))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        headerTitlePanel.setBackground(new java.awt.Color(255, 255, 255));
        headerTitlePanel.setName("headerTitlePanel"); // NOI18N

        navIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/nav_icon.png"))); // NOI18N
        navIconLabel.setName("navIconLabel"); // NOI18N

        clientControlPanelLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        clientControlPanelLabel2.setForeground(new java.awt.Color(0, 36, 109));
        clientControlPanelLabel2.setText(bundle.getString("ClientMessaging.clientControlPanelLabel2.text_1")); // NOI18N
        clientControlPanelLabel2.setName("clientControlPanelLabel2"); // NOI18N

        clientControlPanelLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        clientControlPanelLabel1.setForeground(new java.awt.Color(0, 36, 109));
        clientControlPanelLabel1.setText(bundle.getString("ClientMessaging.clientControlPanelLabel1.text_1")); // NOI18N
        clientControlPanelLabel1.setName("clientControlPanelLabel1"); // NOI18N

        javax.swing.GroupLayout headerTitlePanelLayout = new javax.swing.GroupLayout(headerTitlePanel);
        headerTitlePanel.setLayout(headerTitlePanelLayout);
        headerTitlePanelLayout.setHorizontalGroup(
            headerTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navIconLabel)
                .addGap(18, 18, 18)
                .addComponent(clientControlPanelLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientControlPanelLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerTitlePanelLayout.setVerticalGroup(
            headerTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerTitlePanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(headerTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navIconLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clientControlPanelLabel2)
                        .addComponent(clientControlPanelLabel1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(headerNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(serverDetailsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(serverDetailsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clientDetailsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(clientDetailsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userMessagingSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addGap(2, 2, 2)
                                .addComponent(userMessagingMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(userMessagingTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(headerTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headerNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(headerTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientDetailsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientDetailsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serverDetailsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serverDetailsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(userMessagingTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userMessagingSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(userMessagingMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName(bundle.getString("ClientMessaging.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temporaryStartListenerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temporaryStartListenerButtonActionPerformed
        this.client = new ClientManager("127.0.0.1", 9090, "Listener", "localhost", 9092);
        temporarySenderIdentifierTextBox.setText("Speaker");
        // while (true) {
        //         Message messageObj = this.listener.getMessage();
        //         if (messageObj != null) {
        //             showMessageDialog(null, "Sender: " + messageObj.sender + " - " + "Message: " + messageObj.message);
        //         }
        //     }
    }//GEN-LAST:event_temporaryStartListenerButtonActionPerformed

    private void temporaryStartClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temporaryStartClientButtonActionPerformed
        this.client = new ClientManager("127.0.0.1", 9090, "Speaker", "localhost", 9091);
        temporarySenderIdentifierTextBox.setText("Listener");
    }//GEN-LAST:event_temporaryStartClientButtonActionPerformed

    private void userMessagesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMessagesButtonActionPerformed
        this.client.sendMessage(temporarySenderIdentifierTextBox.getText(), userMessagesTextfield.getText());
    }//GEN-LAST:event_userMessagesButtonActionPerformed

    private void startExampleOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startExampleOneButtonActionPerformed
        this.client = new ClientManager("127.0.0.1", 9090, "Example1", "localhost", 9091);
        temporarySenderIdentifierTextBox.setText("Example1");
    }//GEN-LAST:event_startExampleOneButtonActionPerformed

    private void startExampleTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startExampleTwoButtonActionPerformed
        this.client = new ClientManager("127.0.0.1", 9090, "Example2", "localhost", 9094);
        temporarySenderIdentifierTextBox.setText("Example3");
    }//GEN-LAST:event_startExampleTwoButtonActionPerformed

    private void startExampleThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startExampleThreeButtonActionPerformed
        this.client = new ClientManager("127.0.0.1", 9090, "Example3", "localhost", 9095);
        temporarySenderIdentifierTextBox.setText("Example3");
    }//GEN-LAST:event_startExampleThreeButtonActionPerformed

    private void footerLicensesTextLabelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_footerLicensesTextLabelMouseClicked
        InterfaceManager.changeWindow(this, new Licenses());
    }// GEN-LAST:event_footerLicensesTextLabelMouseClicked

    private void userMessagesButtonMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_userMessagesButtonMouseEntered
      InterfaceManager.buttonHover(userMessagesButton, true, "small");
    }//GEN-LAST:event_userMessagesIconLabelMouseEntered

    private void userMessagesTextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userMessagesTextfieldFocusGained
        InterfaceManager.toggleTextFieldFocus(userMessagesTextfield, true);
    }//GEN-LAST:event_userMessagesTextfieldFocusGained

    private void userMessagesTextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userMessagesTextfieldFocusLost
        InterfaceManager.toggleTextFieldFocus(userMessagesTextfield, false);
    }//GEN-LAST:event_userMessagesTextfieldFocusLost

    private void userMessagesIconLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMessagesIconLabelMouseClicked
        // this.client.
        this.client.sendMessage("Listener", userMessagesTextfield.getText());
    }//GEN-LAST:event_userMessagesIconLabelMouseClicked

    private void userMessagesIconLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMessagesIconLabelMouseEntered
        InterfaceManager.buttonHover(userMessagesButton, true, "small");
    }//GEN-LAST:event_userMessagesIconLabelMouseEntered

    private void userMessagesIconLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMessagesIconLabelMouseExited
        InterfaceManager.buttonHover(userMessagesButton, false, "small");
    }//GEN-LAST:event_userMessagesIconLabelMouseExited

    private void footerLicensesTextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footerLicensesTextLabelMouseClicked
        InterfaceManager.changeWindow(this, new Licenses());
    }//GEN-LAST:event_footerLicensesTextLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientMessaging.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientMessaging.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientMessaging.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientMessaging.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientMessaging(args[0],args[1],args[2],args[3],args[4]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clientControlPanelLabel1;
    private javax.swing.JLabel clientControlPanelLabel2;
    private javax.swing.JLabel clientDetailsAssignedIDNumberLabel;
    private javax.swing.JLabel clientDetailsAssignedIDNumberValueLabel;
    private javax.swing.JLabel clientDetailsConnectionPortLabel;
    private javax.swing.JLabel clientDetailsConnectionPortValueLabel;
    private javax.swing.JLabel clientDetailsIPAddressLabel;
    private javax.swing.JLabel clientDetailsIPAddressValueLabel;
    private javax.swing.JLabel clientDetailsIcon;
    private javax.swing.JLabel clientDetailsLabel1;
    private javax.swing.JLabel clientDetailsLabel2;
    private javax.swing.JPanel clientDetailsPanel1;
    private javax.swing.JPanel clientDetailsPanel2;
    private javax.swing.JLabel clientFeaturesLabel;
    private javax.swing.JLabel discussionNetLabel;
    private javax.swing.JLabel exitApplicationLabel;
    private javax.swing.JLabel footerLicensesTextLabel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel footerTextLabel;
    private javax.swing.JPanel headerNamePanel;
    private javax.swing.JPanel headerTitlePanel;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel messagesLabel;
    private javax.swing.JLabel navIconLabel;
    private javax.swing.JLabel rightArrowIcon1;
    private javax.swing.JLabel rightArrowIcon2;
    private javax.swing.JLabel rightArrowIcon3;
    private javax.swing.JLabel rightArrowIcon4;
    private javax.swing.JLabel rightArrowIcon5;
    private javax.swing.JLabel serverDetailsConnectionPortLabel;
    private javax.swing.JLabel serverDetailsConnectionPortValueLabel;
    private javax.swing.JLabel serverDetailsConnectionStatusLabel;
    private javax.swing.JLabel serverDetailsConnectionStatusValueLabel;
    private javax.swing.JLabel serverDetailsIPAddressLabel;
    private javax.swing.JLabel serverDetailsIPAddressValueLabel;
    private javax.swing.JLabel serverDetailsLabel1;
    private javax.swing.JLabel serverDetailsLabel2;
    private javax.swing.JPanel serverDetailsPanel1;
    private javax.swing.JPanel serverDetailsPanel2;
    private javax.swing.JLabel server_details_icon;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton startExampleOneButton;
    private javax.swing.JButton startExampleThreeButton;
    private javax.swing.JButton startExampleTwoButton;
    private javax.swing.JTextField temporarySenderIdentifierTextBox;
    private javax.swing.JButton temporaryStartClientButton;
    private javax.swing.JButton temporaryStartListenerButton;
    private javax.swing.JLabel updateLogsLabel;
    private javax.swing.JLabel userLabel1;
    private javax.swing.JLabel userLabel2;
    private javax.swing.JLabel userLabel3;
    private javax.swing.JLabel userLabel4;
    private javax.swing.JLabel userLabel5;
    private javax.swing.JButton userMessagesButton;
    private javax.swing.JLabel userMessagesIconLabel;
    private javax.swing.JTextField userMessagesTextfield;
    private javax.swing.JLabel userMessagingIconLabel;
    private javax.swing.JLabel userMessagingLabel;
    private javax.swing.JLabel userMessagingLabel1;
    private javax.swing.JLabel userMessagingLabel2;
    private javax.swing.JPanel userMessagingMainPanel;
    private javax.swing.JPanel userMessagingSidePanel;
    private javax.swing.JPanel userMessagingTopPanel;
    private javax.swing.JLabel usersLabel;
    // End of variables declaration//GEN-END:variables
}
