/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package work.universitycourse.comp1549.Interfaces.Client;

import work.universitycourse.comp1549.Components.RoundJTextField;

/**
 *
 * @author Adnan Turan
 * @author Daniel Browne
 * @author Gabriel Netz
 * @author William Phillips
 * 
 */
public class ClientServerConnection extends javax.swing.JFrame {

        /**
         * Creates new form serverConnection
         */
        public ClientServerConnection() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                mainPanel = new javax.swing.JPanel();
                mainImage = new javax.swing.JLabel();
                discussionNetServerConnectionLabel1 = new javax.swing.JLabel();
                discussionNetServerConnectionLabel2 = new javax.swing.JLabel();
                serverIPAddressLabel = new javax.swing.JLabel();
                connectToServerButton = new javax.swing.JButton();
                serverPortLabel = new javax.swing.JLabel();
                serverIPAddressTextbox = new RoundJTextField();
                serverPortTextbox = new RoundJTextField();
                footerTextLabel = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setMinimumSize(new java.awt.Dimension(854, 519));
                setResizable(false);

                mainPanel.setBackground(new java.awt.Color(255, 255, 255));
                mainPanel.setMaximumSize(new java.awt.Dimension(847, 519));
                mainPanel.setMinimumSize(new java.awt.Dimension(847, 519));
                mainPanel.setPreferredSize(new java.awt.Dimension(847, 519));

                mainImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Connect.png"))); // NOI18N

                discussionNetServerConnectionLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
                discussionNetServerConnectionLabel1.setForeground(new java.awt.Color(0, 36, 109));
                discussionNetServerConnectionLabel1.setText("DiscussionNet");

                discussionNetServerConnectionLabel2.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
                discussionNetServerConnectionLabel2.setText("Server Connection");

                serverIPAddressLabel.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
                serverIPAddressLabel
                                .setIcon(new javax.swing.ImageIcon(getClass().getResource("/configure_ip_icon.png"))); // NOI18N
                serverIPAddressLabel.setText("Server IP Address");

                connectToServerButton.setBackground(new java.awt.Color(255, 255, 255));
                connectToServerButton.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
                connectToServerButton.setForeground(new java.awt.Color(255, 255, 255));
                connectToServerButton.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/medium_button_background.png"))); // NOI18N
                connectToServerButton.setText("Connect to Server");
                connectToServerButton.setBorder(null);
                connectToServerButton.setBorderPainted(false);
                connectToServerButton.setContentAreaFilled(false);
                connectToServerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

                serverPortLabel.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
                serverPortLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/port_icon.png"))); // NOI18N
                serverPortLabel.setText("Server Port");

                serverIPAddressTextbox.setForeground(new java.awt.Color(0, 63, 143));
                serverIPAddressTextbox.setMargin(new java.awt.Insets(0, 0, 0, 0));

                serverPortTextbox.setForeground(new java.awt.Color(0, 63, 143));
                serverPortTextbox.setMargin(new java.awt.Insets(0, 0, 0, 0));

                footerTextLabel.setFont(new java.awt.Font("Montserrat", 0, 9)); // NOI18N
                footerTextLabel.setForeground(new java.awt.Color(47, 46, 65));
                footerTextLabel.setText("DiscussionNet V1.0 - © Code Squad 2021 - Software Licenses");

                javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
                mainPanel.setLayout(mainPanelLayout);
                mainPanelLayout.setHorizontalGroup(mainPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainPanelLayout.createSequentialGroup().addGap(78, 78, 78)
                                                .addComponent(mainImage).addGap(79, 79, 79)
                                                .addGroup(mainPanelLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(mainPanelLayout.createSequentialGroup()
                                                                                .addGroup(mainPanelLayout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(mainPanelLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(0, 1, Short.MAX_VALUE)
                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(serverPortLabel)
                                                                                                                                .addComponent(serverIPAddressLabel)
                                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(discussionNetServerConnectionLabel1)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(discussionNetServerConnectionLabel2))))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                mainPanelLayout.createSequentialGroup()
                                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(serverIPAddressTextbox,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(serverPortTextbox))
                                                                                                                                .addGap(66, 66, 66)))
                                                                                .addGap(79, 79, 79))
                                                                .addGroup(mainPanelLayout.createSequentialGroup()
                                                                                .addComponent(connectToServerButton,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                340,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addContainerGap(
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                mainPanelLayout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(footerTextLabel).addGap(292, 292, 292)));
                mainPanelLayout.setVerticalGroup(mainPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainPanelLayout.createSequentialGroup().addGap(187, 187, 187)
                                                .addComponent(mainImage).addContainerGap(151, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout
                                                .createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(mainPanelLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(discussionNetServerConnectionLabel1)
                                                                .addComponent(discussionNetServerConnectionLabel2))
                                                .addGap(18, 18, 18).addComponent(serverIPAddressLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(serverIPAddressTextbox,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30).addComponent(serverPortLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(serverPortTextbox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(connectToServerButton).addGap(106, 106, 106)
                                                .addComponent(footerTextLabel).addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel. For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(ClientServerConnection.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(ClientServerConnection.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(ClientServerConnection.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(ClientServerConnection.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new ClientServerConnection().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton connectToServerButton;
        private javax.swing.JLabel discussionNetServerConnectionLabel1;
        private javax.swing.JLabel discussionNetServerConnectionLabel2;
        private javax.swing.JLabel footerTextLabel;
        private javax.swing.JLabel mainImage;
        private javax.swing.JPanel mainPanel;
        private javax.swing.JLabel serverIPAddressLabel;
        private javax.swing.JTextField serverIPAddressTextbox;
        private javax.swing.JLabel serverPortLabel;
        private javax.swing.JTextField serverPortTextbox;
        // End of variables declaration//GEN-END:variables
}
