package work.universitycourse.comp1549.Interfaces;

import work.universitycourse.comp1549.Modules.InterfaceManager;
import work.universitycourse.comp1549.Interfaces.Client.ClientServerConnection;
import work.universitycourse.comp1549.Interfaces.Server.ServerConfiguration;

/**
 *
 * @author Adnan Turan
 * @author Daniel Browne
 * @author Gabriel Netz
 * @author William Phillips
 * 
 */
public class StartUpInterface extends javax.swing.JFrame {

    /**
     * Creates new form StartUpInterface
     */
    public StartUpInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startUpInterfacePanel = new javax.swing.JPanel();
        existingNetworkLabel = new javax.swing.JLabel();
        createNetworkLabel = new javax.swing.JLabel();
        titleLabel2 = new javax.swing.JLabel();
        titleLabel3 = new javax.swing.JLabel();
        titleLabel1 = new javax.swing.JLabel();
        mainImage = new javax.swing.JLabel();
        configureServerButton = new javax.swing.JButton();
        configureClientButton = new javax.swing.JButton();
        footerTextLabel = new javax.swing.JLabel();
        footerLicensesTextLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DiscussionNet V1.0 ");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(InterfaceManager.programIcon.getImage());
        setMinimumSize(new java.awt.Dimension(854, 519));
        setName("DiscussionNet"); // NOI18N
        setResizable(false);

        startUpInterfacePanel.setBackground(new java.awt.Color(255, 255, 255));
        startUpInterfacePanel.setMaximumSize(new java.awt.Dimension(847, 519));
        startUpInterfacePanel.setMinimumSize(new java.awt.Dimension(847, 519));
        startUpInterfacePanel.setName("startUpInterfacePanel"); // NOI18N
        startUpInterfacePanel.setPreferredSize(new java.awt.Dimension(847, 519));
        InterfaceManager.detectExitRequest(startUpInterfacePanel);
        startUpInterfacePanel.setLayout(null);

        existingNetworkLabel.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        existingNetworkLabel.setForeground(new java.awt.Color(47, 46, 65));
        existingNetworkLabel.setText("I want to connect to an existing network...");
        existingNetworkLabel.setName("existingNetworkLabel"); // NOI18N
        startUpInterfacePanel.add(existingNetworkLabel);
        existingNetworkLabel.setBounds(102, 350, 269, 17);

        createNetworkLabel.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        createNetworkLabel.setForeground(new java.awt.Color(47, 46, 65));
        createNetworkLabel.setText("I want to create a new network...");
        createNetworkLabel.setName("createNetworkLabel"); // NOI18N
        startUpInterfacePanel.add(createNetworkLabel);
        createNetworkLabel.setBounds(506, 350, 208, 17);

        titleLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        titleLabel2.setForeground(new java.awt.Color(0, 36, 109));
        titleLabel2.setText("DiscussionNet");
        titleLabel2.setName("titleLabel2"); // NOI18N
        startUpInterfacePanel.add(titleLabel2);
        titleLabel2.setBounds(348, 269, 175, 30);

        titleLabel3.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        titleLabel3.setForeground(new java.awt.Color(47, 46, 65));
        titleLabel3.setText("Initial Setup");
        titleLabel3.setName("titleLabel3"); // NOI18N
        startUpInterfacePanel.add(titleLabel3);
        titleLabel3.setBounds(529, 269, 143, 30);

        titleLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        titleLabel1.setForeground(new java.awt.Color(47, 46, 65));
        titleLabel1.setText("Welcome To");
        titleLabel1.setName("titleLabel1"); // NOI18N
        startUpInterfacePanel.add(titleLabel1);
        titleLabel1.setBounds(190, 269, 152, 30);

        mainImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphics/welcome_image.png"))); // NOI18N
        mainImage.setName("mainImage"); // NOI18N
        startUpInterfacePanel.add(mainImage);
        mainImage.setBounds(298, 51, 260, 200);

        configureServerButton.setBackground(new java.awt.Color(255, 255, 255));
        configureServerButton.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        configureServerButton.setForeground(new java.awt.Color(255, 255, 255));
        configureServerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/medium.png"))); // NOI18N
        configureServerButton.setText("Configure Server");
        configureServerButton.setBorder(null);
        configureServerButton.setBorderPainted(false);
        configureServerButton.setContentAreaFilled(false);
        configureServerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        configureServerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        configureServerButton.setName("configureServerButton"); // NOI18N
        configureServerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configureServerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configureServerButtonMouseExited(evt);
            }
        });
        configureServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configureServerButtonActionPerformed(evt);
            }
        });
        startUpInterfacePanel.add(configureServerButton);
        configureServerButton.setBounds(428, 373, 367, 69);

        configureClientButton.setBackground(new java.awt.Color(255, 255, 255));
        configureClientButton.setFont(new java.awt.Font("Montserrat", 0, 15)); // NOI18N
        configureClientButton.setForeground(new java.awt.Color(255, 255, 255));
        configureClientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/medium.png"))); // NOI18N
        configureClientButton.setText("Configure Client");
        configureClientButton.setBorder(null);
        configureClientButton.setBorderPainted(false);
        configureClientButton.setContentAreaFilled(false);
        configureClientButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        configureClientButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        configureClientButton.setName("configureClientButton"); // NOI18N
        configureClientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configureClientButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configureClientButtonMouseExited(evt);
            }
        });
        configureClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configureClientButtonActionPerformed(evt);
            }
        });
        startUpInterfacePanel.add(configureClientButton);
        configureClientButton.setBounds(43, 373, 367, 69);

        footerTextLabel.setFont(new java.awt.Font("Montserrat", 0, 9)); // NOI18N
        footerTextLabel.setForeground(new java.awt.Color(47, 46, 65));
        footerTextLabel.setText("DiscussionNet V1.0   -   © Code Squad 2021   -");
        footerTextLabel.setName("footerTextLabel"); // NOI18N
        startUpInterfacePanel.add(footerTextLabel);
        footerTextLabel.setBounds(285, 507, 189, 12);

        footerLicensesTextLabel.setFont(new java.awt.Font("Montserrat", 2, 9)); // NOI18N
        footerLicensesTextLabel.setForeground(new java.awt.Color(47, 46, 65));
        footerLicensesTextLabel.setText("Software Licenses");
        footerLicensesTextLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        footerLicensesTextLabel.setName("footerLicensesTextLabel"); // NOI18N
        footerLicensesTextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                footerLicensesTextLabelMouseClicked(evt);
            }
        });
        startUpInterfacePanel.add(footerLicensesTextLabel);
        footerLicensesTextLabel.setBounds(480, 507, 80, 12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(startUpInterfacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startUpInterfacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("DiscussionNet");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void configureClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configureClientButtonActionPerformed
        InterfaceManager.changeWindow(this, new ClientServerConnection());
    }//GEN-LAST:event_configureClientButtonActionPerformed

    private void configureServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configureServerButtonActionPerformed
        InterfaceManager.changeWindow(this, new ServerConfiguration());
    }//GEN-LAST:event_configureServerButtonActionPerformed

    private void configureClientButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configureClientButtonMouseEntered
        InterfaceManager.buttonHover(configureClientButton, true, "medium");
    }//GEN-LAST:event_configureClientButtonMouseEntered

    private void configureClientButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configureClientButtonMouseExited
        InterfaceManager.buttonHover(configureClientButton, false, "medium");
    }//GEN-LAST:event_configureClientButtonMouseExited

    private void configureServerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configureServerButtonMouseEntered
        InterfaceManager.buttonHover(configureServerButton, true, "medium");
    }//GEN-LAST:event_configureServerButtonMouseEntered

    private void configureServerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configureServerButtonMouseExited
        InterfaceManager.buttonHover(configureServerButton, false, "medium");
    }//GEN-LAST:event_configureServerButtonMouseExited

    private void footerLicensesTextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footerLicensesTextLabelMouseClicked
        InterfaceManager.displayLicenses();
    }//GEN-LAST:event_footerLicensesTextLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUpInterface.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartUpInterface().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configureClientButton;
    private javax.swing.JButton configureServerButton;
    private javax.swing.JLabel createNetworkLabel;
    private javax.swing.JLabel existingNetworkLabel;
    private javax.swing.JLabel footerLicensesTextLabel;
    private javax.swing.JLabel footerTextLabel;
    private javax.swing.JLabel mainImage;
    private javax.swing.JPanel startUpInterfacePanel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel titleLabel2;
    private javax.swing.JLabel titleLabel3;
    // End of variables declaration//GEN-END:variables
}
